# Table of Content
01. Import Libraries
02. Import Data
03. Add Address Column
04. Get Coordinates of Flats from OneMap API
05. Get Missing Coordinates Manually
06. Compile A Complete Flat Coordinates List
07. Add Flat Coordinates to Main Dataframe
08. Export Data

# 01. Import Libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os
import copy
import asyncio     # the library needed for asynchronous operation
import nest_asyncio     # the library that allows nested use of the asyncio event loop, making asyncio compatible with Jupyter notebooks
import aiohttp     # the library that allows asychronous API calls
import time        # time library is used to handle time-related tasks

In [2]:
# Allow nested asyncio calls in Jupyter notebooks
nest_asyncio.apply()

In [3]:
# Adjust setting to allow seeing all the rows in the output of this notebook
pd.options.display.max_rows = None

In [4]:
# Adjust setting to allow seeing all the columns in the output of this notebook
pd.options.display.max_columns = None

# 02. Import Data

In [5]:
# Define the main project folder path
path = r'C:\Users\saich\Desktop\CareerFoundry\Data Immersion\Achievement 6 Advanced Analytics & Dashboard Design\11-2023 HDB Flat Resale Analysis'

In [6]:
flat_resale = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'flat_resale_all (checked).csv'), index_col = 0)

In [7]:
flat_resale.head()

month        town flat_type block       street_name storey_range  \
0  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
4  1990-01-01  ANG MO KIO    3 ROOM   216  ANG MO KIO AVE 1     04 TO 06   

   floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0            31.0        Improved                 1977        9000.0   
1            31.0        Improved                 1977        6000.0   
2            31.0        Improved                 1977        8000.0   
3            31.0        Improved                 1977        6000.0   
4            73.0  New Generation                 1976       47200.0   

   remaining_lease  row_id  
0               86       0  
1               86       1  
2               86       2  
3               86       3  
4               85       4

In [8]:
flat_resale.shape

(915371, 12)

# 03. Add Address Column

To get coordinates information from OneMap API, a complete address is needed for accurate search. 

Address = block + street name

In [9]:
flat_resale['address'] = flat_resale['block'] + ' ' + flat_resale['street_name']

In [10]:
flat_resale.head(10)

month        town flat_type block       street_name storey_range  \
0  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
4  1990-01-01  ANG MO KIO    3 ROOM   216  ANG MO KIO AVE 1     04 TO 06   
5  1990-01-01  ANG MO KIO    3 ROOM   211  ANG MO KIO AVE 3     01 TO 03   
6  1990-01-01  ANG MO KIO    3 ROOM   202  ANG MO KIO AVE 3     07 TO 09   
7  1990-01-01  ANG MO KIO    3 ROOM   235  ANG MO KIO AVE 3     10 TO 12   
8  1990-01-01  ANG MO KIO    3 ROOM   235  ANG MO KIO AVE 3     04 TO 06   
9  1990-01-01  ANG MO KIO    3 ROOM   232  ANG MO KIO AVE 3     01 TO 03   

   floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0            31.0        Improved                 1977        9000.0   
1            31.0        Improved                 1977        6000.0   
2            31.0        Improved                 1977        8000.0   
3            31.0        Improved                 1977        6000.0   
4            73.0  New Generation                 1976       47200.0   
5            67.0  New Generation                 1977       46000.0   
6            67.0  New Generation                 1977       42000.0   
7            67.0  New Generation                 1977       38000.0   
8            67.0  New Generation                 1977       40000.0   
9            67.0  New Generation                 1977       47000.0   

   remaining_lease  row_id               address  
0               86       0  309 ANG MO KIO AVE 1  
1               86       1  309 ANG MO KIO AVE 1  
2               86       2  309 ANG MO KIO AVE 1  
3               86       3  309 ANG MO KIO AVE 1  
4               85       4  216 ANG MO KIO AVE 1  
5               86       5  211 ANG MO KIO AVE 3  
6               86       6  202 ANG MO KIO AVE 3  
7               86       7  235 ANG MO KIO AVE 3  
8               86       8  235 ANG MO KIO AVE 3  
9               86       9  232 ANG MO KIO AVE 3

In [11]:
flat_resale.shape

(915371, 13)

# 04. Get Coordinates of Flats from OneMap API

### 04.1 Extract A List of Unique Flat Addresses

In [12]:
flat_addresses = flat_resale['address'].unique()

In [13]:
flat_addresses

array(['309 ANG MO KIO AVE 1', '216 ANG MO KIO AVE 1',
       '211 ANG MO KIO AVE 3', ..., '673C YISHUN AVE 4',
       '468A YISHUN ST 43', '674B YISHUN AVE 4'], dtype=object)

In [14]:
len(flat_addresses)

9804

### 04.2 Use aiohttp and Rate Limiting to Get Coordinates Data from OneMap API

In [17]:
# The URL that connects with OneMap API
url = 'https://onemap.sg/api/common/elastic/search?searchVal={}&returnGeom=Y&getAddrDetails=Y&pageNum=1'

# 'start' here indicates the starting time of the retrieval process
# The time.time() function returns the number of seconds passed since epoch (the point where time begins)
start = time.time()

# These 3 lists below would be the outcome we want
flat_address = []
latitude = []
longitude = []

# Define a coroutine with async def
async def get_coordinates(session, semaphore, address, count): 
    
    # Use async with statement to utilize the Semaphore
    async with semaphore: 
        
        # Using the session created, connect with OneMap API with get() function to get the information from the API
        # await is added as we need to wait the call to complete in the event loop and return a response, else it won't do anything
        response = await session.get(url.format(address))

        # Parse the JSON response using .json() method 
        # await is addded since the response is an awaitable object
        data = await response.json()

        if data['found'] > 0:     # If the number of items found is not zero
            lat = data['results'][0]['LATITUDE']
            long = data['results'][0]['LONGITUDE']
        else:                     # If the number of items found is zero
            lat = 'Not found'
            long = 'Not found'
        print('{}) {}, {}, {}'.format(count, address, lat, long))

        # Return the addresses and the coordinates retrieved
        return address, lat, long
    
# Since inside the main() function involve coroutines, add 'async' in front of 'def'
# This tells Python that this function can do asynchronous stuff
async def main(): 
    
    count = 1
    tasks = []
    # Initialize a Semaphore 
    # If Semaphore value is 20, max 20 API calls would be made at the same time. Only 20 calls would be in queue. 
    semaphore = asyncio.Semaphore(20)
    
    # A client session is created to allow the underlying TCP connection to be reused for all requests
    # Using context manager 'with' statement will close the client session automatically when all requests are done
    # Since inside this session involve coroutines, add 'async' in front of 'with'
    async with aiohttp.ClientSession() as session: 
        
        for address in flat_addresses: 
            
            # For each address, create a task of running get_coordinates coroutine using asyncio.create_task()
            # A task will be executed asap whenever there is a stall (await) ongoing
            # When the task is stalled, it will go back to the main caller and run other stuff
            # When the main caller stuff is stalled, it will come back to this task and run the remaining stuff
            # So in our case, while waiting for a response to return, it would start other tasks (making other API calls)
            # Remember to pass the session into get_coordinates coroutine so that a single session is used for all requests
            # Create a list of tasks using .append method
            tasks.append(asyncio.create_task(get_coordinates(session, semaphore, address, count)))
            count += 1
        
        # After creating a list of tasks, gather all the tasks created using asyncio.gather()
        # Since the tasks is inside a list, use *tasks to unpack the tasks inside the list
        # await is added to execute all the task and wait them to finish
        # Store the returned values in variable 'results'
        results = await asyncio.gather(*tasks)
    
    fail = 0
    # The result of asyncio.gather(*tasks) is a list of tuples
    # Each tuple contains a address, its latitude and longitude returned by get_coordinates coroutine
    for result_tuple in results: 
        
        address, lat, long = result_tuple
        flat_address.append(address)
        latitude.append(lat)
        longitude.append(long)
        
        if lat == 'Not found': 
            fail += 1
    
    print('A total of {} failed search'.format(fail))

# Run the event loop (the loop of an asynchronous operation) by running main()
asyncio.run(main())

# 'end' here indicates the ending time of the retrieval process
end = time.time()
total_time = end - start
print('Total {} seconds used'.format(total_time))

20) 345 ANG MO KIO AVE 3, 1.36748702509964, 103.849651723914
3) 211 ANG MO KIO AVE 3, 1.369196965617, 103.841666636086
4) 202 ANG MO KIO AVE 3, 1.36844644010937, 103.844516260527
15) 329 ANG MO KIO AVE 3, 1.3665990830055, 103.846874423696
19) 343 ANG MO KIO AVE 3, 1.36837475142719, 103.849151106677
11) 320 ANG MO KIO AVE 1, 1.3655924562134, 103.848386744168
8) 220 ANG MO KIO AVE 1, 1.36558833593063, 103.840518883254
22) 121 ANG MO KIO AVE 3, 1.36970563478325, 103.843515981311
24) 130 ANG MO KIO AVE 3, 1.37039791675237, 103.841878840032
12) 252 ANG MO KIO AVE 4, Not found, Not found
26) 127 ANG MO KIO AVE 3, 1.37122322102767, 103.843593321222
21) 346 ANG MO KIO AVE 3, 1.36709586875167, 103.84966230288
25) 128 ANG MO KIO AVE 3, 1.37083202800001, 103.843546990613
23) 129 ANG MO KIO AVE 3, 1.36989498895756, 103.842059049722
27) 126 ANG MO KIO AVE 3, 1.37164990020956, 103.843644176374
28) 403 ANG MO KIO AVE 10, 1.36126901451361, 103.854642365822
32) 418 ANG MO KIO AVE 10, 1.3649460137791, 1

151) 87 BEDOK NTH ST 4, 1.33250261426447, 103.938587125421
155) 401 BEDOK NTH AVE 3, 1.33098173461878, 103.933604621756
158) 418 BEDOK NTH AVE 2, 1.32856421177174, 103.930036524233
157) 416 BEDOK NTH AVE 2, 1.32840382815915, 103.930684870347
156) 425 BEDOK NTH RD, 1.32936960154503, 103.929067536324
159) 424 BEDOK NTH AVE 1, 1.32842000962637, 103.927482677521
161) 136 BEDOK NTH AVE 3, 1.32815498828204, 103.93522082327
160) 419 BEDOK NTH ST 1, 1.32697958373998, 103.92813074959
162) 529 BEDOK NTH ST 3, 1.33426946144275, 103.926542284602
163) 510 BEDOK NTH ST 3, 1.33212313291916, 103.93105149637
164) 525 BEDOK NTH ST 3, 1.33460113941761, 103.929445271638
166) 218 BEDOK NTH ST 1, 1.32749295541456, 103.934249434214
165) 202 BEDOK NTH ST 1, 1.32565628436985, 103.927990975389
167) 213 BEDOK NTH ST 1, 1.32633302564898, 103.932636597017
168) 532 BEDOK NTH ST 3, 1.33419173917878, 103.925386600613
170) 536 BEDOK NTH ST 3, 1.3335411894605, 103.923190774432
169) 533 BEDOK NTH ST 3, 1.33358016248275,

306) 44 TELOK BLANGAH DR, 1.27140883340015, 103.810887524155
303) 33 TAMAN HO SWEE, Not found, Not found
307) 46 TELOK BLANGAH DR, 1.27169061066277, 103.809852257535
309) 110 DEPOT RD, 1.28138753916039, 103.809362548941
308) 103 DEPOT RD, 1.28131574987693, 103.807861854014
312) 133 JLN BT MERAH, 1.27955093259631, 103.82740093837
314) 77 INDUS RD, 1.29113483646901, 103.826764453591
311) 132 JLN BT MERAH, 1.27873808127932, 103.828304288385
313) 96 HENDERSON RD, 1.28754332229134, 103.821335072268
310) 42 TELOK BLANGAH RISE, 1.2709187086214, 103.822685388438
315) 78 INDUS RD, 1.29130442807028, 103.827447793798
317) 130 BT MERAH VIEW, 1.28458712798457, 103.824360319186
321) 105 HENDERSON CRES, 1.29021420176947, 103.822356844711
316) 128 BT MERAH VIEW, 1.28264675199072, 103.823327111496
323) 8 TELOK BLANGAH CRES, 1.27779539068994, 103.819341303524
319) 114 BT MERAH VIEW, Not found, Not found
318) 119 BT MERAH VIEW, 1.28342247684697, 103.821068227228
320) 5 TELOK BLANGAH CRES, 1.2787240290542

460) 315 CLEMENTI AVE 4, 1.31847036567508, 103.765419463873
461) 311 CLEMENTI AVE 4, 1.31935456047475, 103.7651093416
462) 301 CLEMENTI AVE 4, 1.32217649495476, 103.764912144396
463) 609 CLEMENTI WEST ST 1, 1.30409242562108, 103.765522148085
464) 729 CLEMENTI WEST ST 2, 1.30492724290307, 103.763519401903
466) 371 CLEMENTI AVE 4, 1.32057465713359, 103.768211873157
465) 707 CLEMENTI WEST ST 2, 1.30628748271347, 103.762394965532
467) 205 CLEMENTI AVE 6, 1.3210599628039, 103.762434749863
469) 415 C'WEALTH AVE WEST, 1.31098804719696, 103.771585053355
468) 414 C'WEALTH AVE WEST, 1.31158107279643, 103.771625045985
470) 413 C'WEALTH AVE WEST, 1.31134730442536, 103.771097378247
471) 336 CLEMENTI AVE 2, 1.31667943214563, 103.769231150532
472) 337 CLEMENTI AVE 2, 1.31605567747075, 103.769112678697
474) 723 CLEMENTI WEST ST 2, 1.30310124001611, 103.763413053663
476) 103 CLEMENTI ST 14, 1.32258854750628, 103.769176205799
473) 717 CLEMENTI WEST ST 2, 1.30323440870789, 103.762464847394
477) 204 CLEME

613) 408 PANDAN GDNS, 1.31820397685545, 103.74881622665
614) 218 JURONG EAST ST 21, 1.34033241177285, 103.737928007136
612) 251 JURONG EAST ST 24, 1.34316585637535, 103.73967649195
615) 322 JURONG EAST ST 31, 1.34803793215272, 103.729165542694
610) 316 JURONG EAST ST 32, 1.34600652715087, 103.732079814028
611) 232 JURONG EAST ST 21, 1.33982600141552, 103.740822151959
616) 227 JURONG EAST ST 21, 1.34182066937117, 103.736087793751
618) 103 JURONG EAST ST 13, 1.33668715015786, 103.738059200285
617) 109 JURONG EAST ST 13, 1.3383617052828, 103.735911158508
619) 240 JURONG EAST ST 21, 1.34106751096494, 103.741573199896
620) 258 JURONG EAST ST 24, 1.34378634902456, 103.738635757888
622) 324 JURONG EAST ST 31, 1.3486489933486, 103.729868988347
621) 209 JURONG EAST ST 21, 1.33782546503407, 103.740093358961
625) 403 PANDAN GDNS, 1.32032964075934, 103.74939013157
623) 331 JURONG EAST AVE 1, 1.35082650419629, 103.73042009299
624) 405 PANDAN GDNS, 1.31923420667707, 103.749654325298
626) 404 PANDAN 

757) 12 NTH BRIDGE RD, 1.30431042727382, 103.862781478293
758) 35 MARINE CRES, 1.30305814475829, 103.912816496021
759) 66 MARINE DR, 1.30391193028103, 103.909740471499
760) 67 MARINE DR, 1.30445136012651, 103.90964857031
761) 4 MARINE TER, 1.30509642100259, 103.917733747552
763) 32 MARINE CRES, 1.303178277126, 103.911806642809
762) 19 MARINE TER, 1.30452210196584, 103.915054010998
764) 31 MARINE CRES, 1.30370556638513, 103.911444787591
765) 30 MARINE CRES, 1.30422279476766, 103.911164021354
769) 43 MARINE CRES, 1.3055188809192, 103.913021967404
766) 7 MARINE TER, 1.30409794254107, 103.917275409766
771) 72 MARINE DR, 1.30428356986834, 103.908364873073
770) 73 MARINE DR, 1.30380541604563, 103.908362369014
767) 62 MARINE DR, 1.30267023304987, 103.909040353592
774) 3 MARINE TER, 1.30410606657184, 103.917733367516
773) 78 MARINE DR, 1.30155231275164, 103.908408095825
768) 55 MARINE TER, 1.30542368483748, 103.914004754803
777) 14 MARINE TER, 1.30347617922703, 103.915411740341
778) 82 C'WEALT

903) 234 TAMPINES ST 21, 1.35590413566011, 103.948024616734
908) 270 TAMPINES ST 21, 1.34963011004171, 103.948635174972
899) 150 TAMPINES ST 12, 1.35094609975013, 103.943260115057
912) 252 TAMPINES ST 21, 1.35254702298525, 103.949064113036
911) 258 TAMPINES ST 21, 1.35433851523618, 103.950029531311
910) 157 TAMPINES ST 12, 1.35107329077378, 103.945003856886
907) 271 TAMPINES ST 21, 1.34980832347153, 103.949577963482
909) 420 TAMPINES ST 41, 1.35786466213391, 103.947534562834
914) 819 TAMPINES ST 81, 1.3483964837387, 103.936808711751
913) 820 TAMPINES ST 81, 1.347929652568, 103.936119933977
915) 217 TAMPINES ST 23, 1.35416816346776, 103.951861755793
916) 215 TAMPINES ST 23, 1.35466443138885, 103.953165900686
918) 810 TAMPINES AVE 4, 1.34645463315474, 103.936611366113
917) 813 TAMPINES ST 81, 1.34695081847394, 103.936416159541
920) 265 TAMPINES ST 21, 1.35245349194636, 103.950238896388
921) 286 TAMPINES ST 22, 1.34953667920762, 103.952988196976
919) 266 TAMPINES ST 21, 1.35196574894384, 

1053) 712 YISHUN AVE 5, 1.42785215049801, 103.827781339299
1047) 36 MARSILING DR, 1.44532379604885, 103.772192712434
1055) 742 YISHUN AVE 5, 1.42972007631008, 103.833109444064
1056) 138 YISHUN RING RD, 1.43160991206918, 103.830614068732
1050) 107 YISHUN RING RD, 1.43221807625653, 103.827520202898
1058) 121 YISHUN ST 11, 1.43436897707941, 103.830142952357
1059) 215 YISHUN ST 21, 1.43174084979873, 103.835660042979
1057) 136 YISHUN RING RD, 1.43203129125603, 103.831436163973
1054) 736 YISHUN ST 72, 1.42865838624933, 103.831727606169
1060) 216 YISHUN ST 21, 1.4322759133834, 103.836404106464
1061) 217 YISHUN ST 21, 1.43262267614989, 103.836318733123
1062) 219 YISHUN ST 21, 1.43331614582593, 103.836150284922
1065) 128 YISHUN ST 11, 1.43387793728634, 103.831302218611
1064) 137 YISHUN RING RD, 1.43198319567796, 103.830253382367
1063) 143 YISHUN RING RD, 1.43100259364042, 103.831093779909
1066) 254 YISHUN RING RD, 1.43461891745071, 103.840583866502
1067) 262 YISHUN ST 22, 1.4357801119708, 103.8

1189) 719 BEDOK RESERVOIR RD, 1.33641984694912, 103.92483267275
1193) 206 BT BATOK ST 21, 1.34667192602747, 103.749383473832
1192) 312 SHUNFU RD, 1.35120461586182, 103.838716846527
1191) 307 SHUNFU RD, 1.35048016607758, 103.838771255828
1194) 207 BT BATOK ST 21, 1.34624866176031, 103.749382188265
1197) 136 BT BATOK WEST AVE 6, 1.35090042870513, 103.74485764967
1195) 167 BT BATOK WEST AVE 8, 1.34693272783596, 103.742257105901
1199) 213 BT BATOK ST 21, 1.34681845451426, 103.752496875347
1198) 175 BT BATOK WEST AVE 8, 1.34554897953938, 103.741598629749
1196) 139 BT BATOK WEST AVE 6, 1.35110319953225, 103.744169896472
1202) 240 BT BATOK EAST AVE 5, 1.35048816023777, 103.754177773165
1200) 215 BT BATOK ST 21, 1.34677496983575, 103.753335935038
1201) 239 BT BATOK EAST AVE 5, 1.3502391390638, 103.755100850762
1204) 237 BT BATOK EAST AVE 5, 1.34949080174397, 103.755305492466
1203) 242 BT BATOK EAST AVE 5, 1.35095950808957, 103.756233418128
1209) 105 BT BATOK CTRL, 1.3485726542005, 103.74715622

1331) 5 YUNG PING RD, Not found, Not found
1333) 113 TAO CHING RD, 1.33318449829266, 103.724354324887
1337) 425 JURONG WEST AVE 1, 1.35085080574192, 103.724437331849
1336) 207 BOON LAY PL, 1.34658610279641, 103.71356835409
1335) 171 BOON LAY DR, Not found, Not found
1334) 142 HU CHING RD, Not found, Not found
1327) 212 JURONG EAST ST 21, 1.33909401436064, 103.740391980229
1338) 462 JURONG WEST ST 41, 1.35065966569769, 103.722348235699
1332) 6 YUNG PING RD, Not found, Not found
1339) 475 JURONG WEST ST 41, 1.34809804107273, 103.725087226378
1341) 528 JURONG WEST ST 52, 1.34831968709824, 103.71695546848
1343) 514 JURONG WEST ST 52, 1.34674845635984, 103.720153220929
1344) 437 JURONG WEST AVE 1, 1.35157134078567, 103.723964571541
1345) 451 JURONG WEST ST 42, 1.35187874821928, 103.718501587999
1346) 449 JURONG WEST ST 42, 1.35234799631864, 103.718438388228
1347) 403 JURONG WEST ST 42, 1.35383921849512, 103.721479697852
1348) 430 JURONG WEST AVE 1, 1.3519543113972, 103.725622636589
1349) 48

1474) 17 MARSILING LANE, 1.44267823126467, 103.77772450872
1478) 145 WOODLANDS ST 13, 1.4361178671849, 103.773245421824
1476) 23 MARSILING DR, 1.44153974863437, 103.773299897996
1480) 33 MARSILING DR, 1.44355825410306, 103.772015392214
1472) 230 LOR 8 TOA PAYOH, 1.33825592680641, 103.859303071005
1479) 155 WOODLANDS ST 13, 1.43473447528056, 103.774586932224
1466) 219 LOR 8 TOA PAYOH, 1.34276433135393, 103.855872559035
1481) 37 MARSILING DR, 1.44554176156168, 103.771709178755
1475) 30 MARSILING DR, 1.44255907448697, 103.772405528859
1477) 32 MARSILING DR, 1.44337609848317, 103.772918121132
1471) 223 LOR 8 TOA PAYOH, 1.34126479712806, 103.855552754659
1484) 111 YISHUN RING RD, 1.43321263970177, 103.828617498413
1482) 114 YISHUN RING RD, 1.43413792566359, 103.827020312888
1483) 117 YISHUN RING RD, 1.43555874650871, 103.827699051305
1485) 709 YISHUN AVE 5, 1.4285690021208, 103.827735428264
1487) 741 YISHUN AVE 5, 1.43010019275338, 103.833117595994
1488) 134 YISHUN ST 11, 1.43237650538302, 

1626) 715 CLEMENTI WEST ST 2, 1.30315360303876, 103.761943675943
1633) 97 ALJUNIED CRES, 1.32130121230561, 103.885672031668
1627) 338 CLEMENTI AVE 2, 1.3162903980152, 103.769532089119
1631) 10 HAIG RD, 1.31483950176268, 103.895865169739
1629) 203 CLEMENTI AVE 6, 1.32077128251778, 103.76231687576
1602) 114 DEPOT RD, 1.28175927117793, 103.806862236642
1596) 40 TELOK BLANGAH RISE, 1.27209926567831, 103.823245112725
1634) 101 ALJUNIED CRES, 1.32092275330579, 103.883351967045
1635) 66 CIRCUIT RD, 1.32653588159213, 103.887672820976
1630) 43 CIRCUIT RD, 1.32648228290473, 103.885544901533
1628) 604 CLEMENTI WEST ST 1, 1.30542777397595, 103.767493297152
1636) 64 CIRCUIT RD, 1.32698404492367, 103.887148432844
1640) 323 UBI AVE 1, 1.32803365560415, 103.904398329853
1637) 19 BALAM RD, 1.33142362640009, 103.887410301919
1623) 317 CLEMENTI AVE 4, 1.31803800701388, 103.764519142282
1644) 320 UBI AVE 1, 1.32880527103033, 103.904280456723
1641) 121 PAYA LEBAR WAY, 1.32192501630432, 103.882860355973
163

1769) 211 SERANGOON AVE 4, 1.35633276245751, 103.873366015559
1770) 216 SERANGOON AVE 4, 1.35754563359063, 103.873252175576
1767) 232 SERANGOON AVE 3, 1.35474706561703, 103.868731989138
1775) 205 TAMPINES ST 21, 1.35171765014011, 103.951963085466
1773) 310 SERANGOON AVE 2, 1.35362308168848, 103.865716642199
1776) 907 TAMPINES AVE 4, 1.35061228147276, 103.939397414558
1772) 121 SERANGOON NTH AVE 1, 1.36693542180082, 103.8712847222
1771) 301 SERANGOON AVE 2, 1.35288347756585, 103.867822811475
1778) 282 TAMPINES ST 22, 1.34775409909298, 103.952436774993
1780) 243 TAMPINES ST 21, 1.35419527444806, 103.947122094105
1777) 108 TAMPINES ST 11, 1.34786646438205, 103.94856161626
1781) 249 TAMPINES ST 21, 1.35186837515817, 103.948463265355
1774) 123 SERANGOON NTH AVE 1, 1.3669585129808, 103.872593551192
1783) 246 TAMPINES ST 21, 1.35322549774418, 103.947232182338
1784) 292 TAMPINES ST 22, 1.35018359420823, 103.955775653808
1779) 144 TAMPINES ST 12, 1.34841857750645, 103.943725846535
1782) 421 TAM

1922) 20 TELOK BLANGAH CRES, 1.27691594809877, 103.821818722889
1919) 90 ZION RD, Not found, Not found
1929) 128 KIM TIAN RD, 1.28152464770049, 103.829054629386
1924) 3 REDHILL CL, Not found, Not found
1925) 16 TAMAN HO SWEE, 1.2880016960752, 103.831614592325
1930) 24 TELOK BLANGAH CRES, 1.27540949062767, 103.820660541826
1920) 15 TELOK BLANGAH CRES, 1.27698913358023, 103.820541104343
1927) 54 NILE RD, Not found, Not found
1928) 24 JLN MEMBINA BARAT, Not found, Not found
1923) 8 REDHILL CL, Not found, Not found
1926) 51 NILE RD, Not found, Not found
1933) 104 HENDERSON CRES, 1.2893692748935, 103.821538089569
1932) 59 TELOK BLANGAH HTS, 1.2753534329115, 103.813588303131
1934) 95 HAVELOCK RD, 1.28847543074122, 103.832848165751
1935) 26 TELOK BLANGAH CRES, 1.27669324661085, 103.818866609662
1938) 3 TG PAGAR PLAZA, 1.2756191858993, 103.842431306625
1936) 5 FARRER RD, 1.31655990980042, 103.807288102167
1937) 10 JLN KUKOH, 1.2869738344398, 103.839075823483
1941) 668 CHANDER RD, 1.30758124026

2076) 194 KIM KEAT AVE, 1.33093933675526, 103.858181909317
2084) 731 YISHUN ST 72, 1.4283470473707, 103.831118755408
2082) 172 WOODLANDS ST 13, 1.43398859274828, 103.777490482198
2083) 215 MARSILING LANE, 1.4476075755764, 103.772062005139
2085) 125 YISHUN ST 11, 1.4339506942268, 103.830439843368
2077) 104 POTONG PASIR AVE 1, 1.3343391689203, 103.869158899303
2088) 255 YISHUN RING RD, 1.43431631548686, 103.840689452912
2089) 278 YISHUN ST 22, 1.43831415037996, 103.838226869973
2090) 754 YISHUN ST 72, 1.42688859174215, 103.834067042338
2092) 139 YISHUN RING RD, 1.43165616021317, 103.831319107107
2086) 214 YISHUN ST 21, 1.43144616456684, 103.836318885001
2091) 749 YISHUN ST 72, 1.42837595256793, 103.834113498541
2093) 236 YISHUN RING RD, 1.43403211971292, 103.83882419471
2087) 124 YISHUN ST 11, 1.43459030044018, 103.831139296919
2096) 805 YISHUN RING RD, 1.41742722691875, 103.831588869701
2100) 325 ANG MO KIO AVE 3, 1.36789986956821, 103.846887401387
2099) 113 ANG MO KIO AVE 4, 1.37178518

2222) 224 LOR 8 TOA PAYOH, 1.34117607884148, 103.85606624411
2231) 202 YISHUN ST 21, 1.43066191912434, 103.837334321945
2232) 133 YISHUN ST 11, 1.43255737199893, 103.830784110499
2234) 253 YISHUN RING RD, 1.43507473889027, 103.840795048444
2239) 119 ANG MO KIO AVE 3, 1.36956344301912, 103.844698910817
2233) 227 YISHUN ST 21, 1.435069715602, 103.836644751474
2238) 256 YISHUN RING RD, 1.43409342070863, 103.839979155802
2237) 246 YISHUN AVE 9, 1.43509085774181, 103.84269104902
2236) 230 YISHUN ST 21, 1.43457623282091, 103.836620800984
2240) 649 ANG MO KIO AVE 5, 1.37776263842074, 103.843782193293
2235) 228 YISHUN ST 21, 1.43533747562924, 103.837523010219
2244) 327 ANG MO KIO AVE 3, 1.36705284380639, 103.846987446489
2242) 635 ANG MO KIO AVE 6, 1.38076896104696, 103.842378423538
2241) 540 ANG MO KIO AVE 10, 1.37529376778898, 103.855452425625
2246) 426 ANG MO KIO AVE 3, 1.36948046776679, 103.853309796692
2247) 636 ANG MO KIO AVE 6, 1.38115265431721, 103.843310287802
2243) 153 ANG MO KIO AVE

2387) 266 BT BATOK EAST AVE 4, 1.34936030465417, 103.760019454103
2383) 368 BT BATOK ST 31, 1.36038104862798, 103.750923865594
2384) 201 BT BATOK ST 21, 1.34586253909028, 103.747905760698
2390) 245 BT BATOK EAST AVE 5, 1.3496481268301, 103.757332776738
2388) 144 BT BATOK WEST AVE 6, 1.3500433867981, 103.744237408407
2389) 212 BT BATOK ST 21, 1.34719281119437, 103.752217334445
2396) 77 TELOK BLANGAH DR, 1.27395376732331, 103.808817470502
2395) 108 BT PURMEI RD, 1.27337413706546, 103.825328120716
2394) 131 JLN BT MERAH, 1.2801894226101, 103.828178445611
2397) 142 JLN BT MERAH, 1.27700823497374, 103.828056201882
2393) 31 TELOK BLANGAH RISE, 1.27239732679697, 103.820832735739
2391) 306 BT BATOK ST 31, 1.3582878390455, 103.747520379156
2392) 370 BT BATOK ST 31, 1.3599840040253, 103.749882092542
2400) 107 JLN BT MERAH, 1.27983690191197, 103.824757769108
2398) 17 REDHILL CL, Not found, Not found
2399) 2 REDHILL CL, Not found, Not found
2401) 29 LIM LIAK ST, 1.28538144338708, 103.830400732841


2535) 281 YISHUN ST 22, 1.43896457843625, 103.837500561028
2531) 755 YISHUN ST 72, 1.42707820696356, 103.832706088136
2528) 232 YISHUN ST 21, 1.43459992009659, 103.837409471332
2537) 114 ANG MO KIO AVE 4, 1.37257962452704, 103.836220813247
2534) 643 YISHUN ST 61, 1.42133515867973, 103.837436986724
2533) 724 YISHUN ST 71, 1.42647481851247, 103.82991593847
2536) 321 ANG MO KIO AVE 1, 1.36514126911853, 103.8487041858
2540) 554 ANG MO KIO AVE 10, 1.37282000844329, 103.857784026362
2542) 311 ANG MO KIO AVE 3, 1.36663973560866, 103.848769708749
2543) 437 ANG MO KIO AVE 10, 1.36720027552413, 103.853247443819
2541) 207 ANG MO KIO AVE 1, 1.36582089504381, 103.842847772078
2546) 546 BEDOK NTH ST 3, 1.33082005919243, 103.925595840288
2550) 624 BEDOK RESERVOIR RD, 1.33430060482328, 103.916398118478
2544) 123 BEDOK NTH ST 2, 1.32919868667839, 103.937343347878
2545) 542 BEDOK NTH ST 3, 1.33066590908483, 103.922843972485
2551) 147 BEDOK RESERVOIR RD, 1.33488194247883, 103.911778859623
2529) 272 YISHU

2681) 9 HAIG RD, 1.31443381495978, 103.896061149264
2685) 11 HAIG RD, 1.31483626965284, 103.896637295254
2684) 347 UBI AVE 1, 1.32566116950868, 103.899733223176
2688) 844 SIMS AVE, 1.31818343943101, 103.901311204958
2683) 54 CASSIA CRES, 1.31004800551081, 103.884678198119
2691) 405 HOUGANG AVE 10, 1.37404969557747, 103.896459281626
2682) 17 EUNOS CRES, 1.32337014878712, 103.904403708711
2686) 348 UBI AVE 1, 1.32615026018563, 103.900527500118
2690) 122 HOUGANG AVE 1, 1.35374408051544, 103.886159336002
2689) 6 HOUGANG AVE 3, 1.36271446291047, 103.893980503167
2687) 330 UBI AVE 1, 1.32650643553954, 103.904049563769
2693) 116 JURONG EAST ST 13, 1.33970763311095, 103.734697751981
2692) 313 JURONG EAST ST 32, 1.34715455988215, 103.733348701413
2694) 234 JURONG EAST ST 21, 1.3399327053569, 103.741646605612
2695) 309 JURONG EAST ST 32, 1.34753691047157, 103.734033285066
2697) 557 JURONG WEST ST 42, 1.35399275101832, 103.718567124767
2696) 524 JURONG WEST ST 52, 1.3471976255018, 103.71724673083

2835) 109 BT PURMEI RD, 1.27392939929265, 103.825310761145
2836) 1 EVERTON PK, 1.27742654288695, 103.840001188095
2837) 5 REDHILL CL, Not found, Not found
2840) 1 TIONG BAHRU RD, 1.28613693561234, 103.833027874167
2838) 72 REDHILL RD, 1.28740502686387, 103.816391960711
2829) 339 BT BATOK ST 34, 1.36319798587253, 103.75080463345
2839) 49 KIM PONG RD, 1.28429935662089, 103.830518003368
2842) 29 KELANTAN RD, 1.30573440556914, 103.857121480845
2846) 631 HOUGANG AVE 8, 1.37069136628932, 103.881518580726
2845) 317 UBI AVE 1, 1.32857757757936, 103.902800620956
2834) 535 BT BATOK ST 52, 1.35497075521286, 103.750399548957
2832) 309 BT BATOK ST 31, 1.35828328143448, 103.748771560551
2841) 107 BT PURMEI RD, 1.27310165475122, 103.824508572172
2848) 333 HOUGANG AVE 5, 1.36849761537181, 103.898423005409
2847) 619 HOUGANG AVE 8, 1.36984770803551, 103.883701202398
2849) 705 HOUGANG AVE 2, 1.36564903485076, 103.888263962373
2843) 535 UPP CROSS ST, 1.28459455749373, 103.846220907456
2851) 250 JURONG EAS

2974) 408 BT BATOK WEST AVE 4, 1.36481977758189, 103.744989792545
2975) 342 BT BATOK ST 34, 1.36258323081948, 103.748574945077
2972) 126 BT BATOK CTRL, 1.35192324053157, 103.746721991089
2979) 143 JLN BT MERAH, 1.27778523331688, 103.830001495464
2973) 232 BT BATOK EAST AVE 5, 1.34933608943668, 103.75494179671
2981) 325 UBI AVE 1, 1.32770471680567, 103.903826117652
2978) 115 BT MERAH CTRL, 1.28412809632853, 103.814543761786
2982) 24 BALAM RD, 1.33018852048052, 103.887508672167
2980) 343 CLEMENTI AVE 5, 1.31790852573142, 103.770934449602
2976) 330 BT BATOK ST 33, 1.36339848689145, 103.748445426437
2984) 333 UBI AVE 1, 1.32669704800522, 103.90298325894
2983) 42 CASSIA CRES, 1.31041140455932, 103.886398004352
2987) 510 HOUGANG AVE 10, 1.37257464057042, 103.88846165069
2990) 621 HOUGANG AVE 8, 1.36991763773226, 103.883193094527
2988) 411 HOUGANG AVE 10, 1.37409413946214, 103.895312625321
2964) 123 BISHAN ST 12, 1.34648720621029, 103.850461077477
2986) 509 HOUGANG AVE 10, 1.37221124042577, 1

3130) 174 YISHUN AVE 7, 1.43739545335207, 103.831939137109
3134) 233 ANG MO KIO AVE 3, 1.36754924977907, 103.836740628478
3128) 335 WOODLANDS ST 32, 1.42972520117129, 103.780579357988
3135) 531 ANG MO KIO AVE 10, 1.37332988150849, 103.854382230482
3141) 343 BT BATOK ST 34, 1.36238776835658, 103.749167455431
3137) 515 BEDOK NTH AVE 2, 1.33186656511661, 103.929960229584
3140) 401 SIN MING AVE, 1.36250549567624, 103.833185320675
3139) 127 BISHAN ST 12, 1.34607589409488, 103.851694780512
3142) 310 BT BATOK ST 32, 1.35964071966908, 103.748829089659
3143) 335 BT BATOK ST 32, 1.36454992483304, 103.748092994225
3133) 633 YISHUN ST 61, 1.41865757414383, 103.839842120968
3138) 120 BISHAN ST 12, 1.34725137775914, 103.850848308399
3136) 543 ANG MO KIO AVE 10, 1.37430114417473, 103.856235581791
3144) 372 BT BATOK ST 31, 1.35866916706906, 103.751213742148
3131) 722 YISHUN ST 71, 1.42566715797556, 103.829016104284
3132) 785 YISHUN AVE 2, 1.42140901096648, 103.833970980379
3149) 337 UBI AVE 1, 1.32598

3263) 127 POTONG PASIR AVE 1, 1.33503445523376, 103.865505631737
3277) 168 BEDOK STH AVE 3, 1.32003554111515, 103.944570078049
3270) 716 YISHUN ST 71, 1.42612488910141, 103.827512567263
3267) 615 YISHUN RING RD, 1.4196134507191, 103.835476274579
3274) 790 YISHUN AVE 2, 1.42000005533967, 103.83379451266
3275) 175 YISHUN AVE 7, 1.43760321425304, 103.832468232948
3260) 145 SERANGOON NTH AVE 1, 1.36780607446741, 103.872379573915
3282) 136 BEDOK RESERVOIR RD, 1.33353806122657, 103.913536944229
3269) 761 YISHUN ST 72, 1.42539842469037, 103.833259035976
3262) 835 TAMPINES ST 83, 1.35113833740958, 103.933863132539
3278) 142 BEDOK RESERVOIR RD, 1.33563649761465, 103.913269358016
3284) 112 BISHAN ST 12, 1.34681029782167, 103.84904106054
3283) 137 BEDOK RESERVOIR RD, 1.33390202913472, 103.913274271807
3279) 63 NEW UPP CHANGI RD, 1.32378410132248, 103.939938951727
3280) 524 BEDOK NTH ST 3, 1.33484035279202, 103.930637846839
3288) 102 BISHAN ST 12, 1.3451431233477, 103.847990805259
3287) 168 BISHAN

3433) 430 HOUGANG AVE 6, 1.37532106170398, 103.893261128732
3431) 697 HOUGANG ST 61, 1.37554033809538, 103.887475138873
3434) 352 JURONG EAST ST 31, 1.34492289474517, 103.730400848037
3435) 929 JURONG WEST ST 92, 1.34129441040099, 103.689270790909
3429) 514 HOUGANG AVE 10, 1.37211670537615, 103.889192688637
3430) 687 HOUGANG ST 61, 1.3762254502561, 103.885072860925
3436) 123 MCNAIR RD, 1.31844233518161, 103.856349883909
3438) 244 SERANGOON AVE 2, 1.35249536436696, 103.868749654582
3432) 521 HOUGANG AVE 6, 1.37339975662977, 103.890974482659
3439) 146 SERANGOON NTH AVE 1, 1.36816861691966, 103.87293845884
3440) 827 TAMPINES ST 81, 1.34971656732554, 103.93372188081
3442) 447 TAMPINES ST 42, 1.35735906297136, 103.950485484376
3445) 124 POTONG PASIR AVE 1, 1.3353470224763, 103.865451584255
3437) 122 PASIR RIS ST 11, 1.36652833508957, 103.954404987572
3441) 844 TAMPINES ST 82, 1.35210299492899, 103.936534321867
3443) 416 TAMPINES ST 41, 1.35915490215513, 103.947401738253
3444) 453 TAMPINES S

3600) 648 HOUGANG AVE 8, 1.37212621537163, 103.87979354211
3597) 120 GEYLANG EAST CTRL, 1.31821153053878, 103.884752333398
3602) 349 JURONG EAST AVE 1, 1.34446375047917, 103.731445785743
3603) 222 JURONG EAST ST 21, 1.34081722087136, 103.735755582653
3598) 669 HOUGANG AVE 8, 1.37337022502161, 103.884099363082
3604) 977 JURONG WEST ST 93, 1.33969365989339, 103.693915380547
3609) 203 TAMPINES ST 21, 1.3522279450458, 103.952437443086
3605) 53 KENT RD, 1.31652542675346, 103.852091950414
3610) 434 TAMPINES ST 43, 1.3592418423449, 103.951613078969
3607) 7 SELETAR WEST FARMWAY 6, Not found, Not found
3599) 530 HOUGANG AVE 6, 1.37516813281876, 103.890119934151
3608) 142 SERANGOON NTH AVE 1, 1.36738923192236, 103.873635517365
3601) 633 HOUGANG AVE 8, 1.36982607247094, 103.879317363374
3611) 201E TAMPINES ST 23, 1.35292162536007, 103.953858335355
3606) 119 PASIR RIS ST 11, 1.36752490300235, 103.954781393933
3612) 220 TAMPINES ST 24, 1.35570486057403, 103.952040568571
3613) 944 TAMPINES AVE 5, 1.

3762) 305 YISHUN CTRL, 1.43086656800412, 103.839425861369
3763) 308 YISHUN RING RD, 1.43122983753347, 103.840559963761
3764) 826 YISHUN ST 81, 1.41417410336287, 103.832454191534
3765) 824 YISHUN ST 81, 1.41374532146112, 103.833303196513
3766) 877 YISHUN ST 81, 1.41390219124124, 103.835453933174
3767) 605 YISHUN ST 61, 1.42172608902193, 103.836336375801
3768) 148 BISHAN ST 11, 1.3442336080746, 103.854763632034
3770) 132 CASHEW RD, 1.37427380230521, 103.770688640795
3775) 136 LOR AH SOO, 1.34966436735423, 103.88630211152
3757) 303 YISHUN CTRL, 1.43026863874417, 103.840067166013
3759) 302 YISHUN CTRL, 1.43003455434607, 103.839674797958
3769) 5 TIONG BAHRU RD, 1.28620043157708, 103.831687678938
3777) 1 KG KAYU RD, 1.30355769675629, 103.883796413118
3774) 246 HOUGANG ST 22, 1.35876258437852, 103.891460074318
3780) 108 SIMEI ST 1, 1.34301954085884, 103.951007442775
3772) 249 BANGKIT RD, 1.3810020467136, 103.774054657076
3771) 221 PENDING RD, 1.37537217237782, 103.773454058862
3781) 149 SIMEI

3904) 282 YISHUN AVE 6, 1.43940871246049, 103.838425107982
3896) 224 PENDING RD, 1.37592215469112, 103.773000511438
3898) 255 BANGKIT RD, 1.37958663519485, 103.773053180398
3901) 40 HOLLAND DR, 1.30717590843196, 103.793500328714
3897) 240 BT PANJANG RING RD, 1.37934514194061, 103.771222864624
3899) 668 HOUGANG AVE 8, 1.37348033489981, 103.883581147753
3900) 920 JURONG WEST ST 92, 1.33981029705454, 103.688318667097
3911) 344 YISHUN AVE 11, 1.4290305000563, 103.84430354208
3906) 828 YISHUN ST 81, 1.41519092970513, 103.832901692682
3907) 405 YISHUN AVE 6, 1.42684012912743, 103.849273522587
3908) 387 YISHUN RING RD, 1.42954682086043, 103.847278941139
3910) 406 YISHUN AVE 6, 1.42607011749044, 103.849303010046
3909) 392 YISHUN AVE 6, 1.42869782501371, 103.849200667368
3912) 139 BEDOK RESERVOIR RD, 1.33462453350019, 103.913777679684
3919) 202 PETIR RD, 1.37219171423657, 103.77484799254
3920) 211 PETIR RD, 1.37466415529251, 103.77614521146
3916) 21 LIM LIAK ST, 1.28543821567121, 103.8321614175

4039) 49 JLN BAHAGIA, 1.32765981551451, 103.856373450584
4041) 427 PASIR RIS DR 6, 1.37030649259799, 103.956014968641
4043) 43 STIRLING RD, 1.29809677101957, 103.802598087788
4040) 47 JLN BAHAGIA, 1.32750482242864, 103.856897098071
4044) 46 STIRLING RD, 1.29844502220148, 103.801577968101
4042) 72 C'WEALTH DR, 1.30002336935165, 103.796956865534
4050) 145 SIMEI ST 2, 1.34484832828898, 103.955553840065
4051) 454 TAMPINES ST 42, 1.3572982230676, 103.955006394373
4049) 863A TAMPINES ST 83, 1.3554642176108, 103.936666074781
4052) 321 WOODLANDS ST 32, 1.43188553711066, 103.779323207159
4056) 345 YISHUN AVE 11, 1.42847591927493, 103.844070961331
4047) 887 TAMPINES ST 81, 1.35046411304959, 103.931896396161
4053) 404 YISHUN AVE 6, 1.42657680751384, 103.84814422982
4057) 863 YISHUN AVE 4, 1.41693951602054, 103.838619903084
4048) 138 SIMEI ST 1, 1.34721811835569, 103.956900531765
4058) 425 YISHUN AVE 11, 1.42242242128485, 103.848326515766
4059) 841 YISHUN ST 81, 1.41601322618783, 103.834368645699


4197) 337 ANG MO KIO AVE 1, 1.36319555672393, 103.851616001112
4203) 235 BT PANJANG RING RD, 1.37818350557282, 103.771291362954
4200) 449 SIN MING AVE, 1.35808106284654, 103.83079059602
4202) 26 TIONG BAHRU RD, 1.28567055710851, 103.830832052892
4199) 101 LENGKONG TIGA, 1.32515983382087, 103.910888819332
4201) 332 BT BATOK ST 32, 1.36375968270148, 103.748197987376
4204) 402 FAJAR RD, 1.38031226320182, 103.768073595
4205) 210 PETIR RD, 1.37419077642517, 103.776256230332
4206) 16 TOH YI DR, 1.33940868079894, 103.772605679864
4208) 121 TECK WHYE LANE, 1.37830357075531, 103.750108106647
4207) 13 TOH YI DR, 1.33874587958197, 103.772438575927
4210) 681 HOUGANG AVE 8, 1.37311063009805, 103.885636629182
4212) 654 HOUGANG AVE 8, 1.37273945323962, 103.881759777908
4209) 142 TECK WHYE LANE, 1.38079049641025, 103.75195441174
4213) 944 JURONG WEST ST 91, 1.34460158675371, 103.689712964527
4215) 482 PASIR RIS DR 4, 1.3737441529967, 103.959755840195
4211) 811 HOUGANG CTRL, 1.37187111601411, 103.89379

4368) 277 CHOA CHU KANG AVE 2, 1.37987227900139, 103.744605644093
4370) 107 TECK WHYE LANE, 1.37805538148223, 103.753588247554
4366) 102 TECK WHYE LANE, 1.377082841385, 103.754394432037
4372) 312 UBI AVE 1, 1.32967348010041, 103.903784250226
4371) 120 TECK WHYE LANE, 1.37884184875046, 103.750340641074
4374) 215 JURONG EAST ST 21, 1.33993327217519, 103.738514477739
4375) 836 JURONG WEST ST 81, 1.34263096431938, 103.693464895067
4356) 205 BISHAN ST 23, 1.35531327191887, 103.847698285024
4376) 946 JURONG WEST ST 91, 1.34420009942757, 103.69045184945
4373) 445 HOUGANG AVE 8, 1.37912308611848, 103.89428875283
4377) 943 JURONG WEST ST 91, 1.343694927282, 103.689789273674
4369) 344 CHOA CHU KANG LOOP, 1.38328262549326, 103.74511032068
4367) 418 CHOA CHU KANG AVE 4, 1.38237300282948, 103.741352257872
4380) 115 PASIR RIS ST 11, 1.36892657029538, 103.954870571077
4379) 918 JURONG WEST ST 91, 1.34057937455948, 103.687170663318
4381) 419 PASIR RIS DR 6, 1.37152385430804, 103.954753075267
4378) 940

4495) 115 LENGKONG TIGA, 1.32297309915876, 103.911228144346
4518) 542 HOUGANG AVE 8, 1.37695171842745, 103.891748637325
4511) 434 CHOA CHU KANG AVE 4, 1.38444682435766, 103.74108952188
4505) 433 BT PANJANG RING RD, 1.38573032403926, 103.771212580732
4514) 683 HOUGANG AVE 8, 1.37331270061833, 103.886367847223
4516) 434 HOUGANG AVE 8, 1.37647221623833, 103.893822106133
4517) 440 HOUGANG AVE 8, 1.37913329229155, 103.893527867739
4515) 420 HOUGANG AVE 10, 1.37580558530644, 103.894819073452
4513) 43A SIMS DR, 1.31681884371364, 103.876639624866
4519) 565 HOUGANG ST 51, 1.38051822975687, 103.887953240185
4520) 431 HOUGANG AVE 6, 1.37563298230886, 103.893107879251
4524) 416 SERANGOON CTRL, 1.35020561451168, 103.87481852314
4521) 953 JURONG WEST ST 91, 1.34234942956379, 103.690874115788
4525) 538 SERANGOON NTH AVE 4, 1.37491459857485, 103.873217877598
4527) 235 SIMEI ST 4, 1.34295970419769, 103.955474153095
4529) 488A TAMPINES AVE 9, 1.36022206338794, 103.956335998151
4522) 725 JURONG WEST AVE 

4645) 425 BT BATOK WEST AVE 2, 1.3618323500025, 103.745225942903
4649) 248 CHOA CHU KANG AVE 2, 1.37900459646071, 103.745926026056
4595) 143 PASIR RIS ST 11, 1.36198405238232, 103.960695828184
4600) 58 STIRLING RD, 1.29619171855669, 103.804541873744
4619) 137 TECK WHYE LANE, 1.38004752975397, 103.752483841199
4655) 476 PASIR RIS DR 6, 1.37519548125055, 103.958359563144
4651) 417 HOUGANG AVE 8, 1.37645924477185, 103.894857328635
4654) 440 PASIR RIS DR 4, 1.36899801064525, 103.958647641559
4658) 522 SERANGOON NTH AVE 4, 1.37263476681332, 103.873398297569
4653) 425 PASIR RIS DR 6, 1.36956993932329, 103.954864275083
4661) 136 MARSILING RD, 1.43832145748732, 103.777752029807
4665) 227 CHOA CHU KANG CTRL, 1.38118249686415, 103.745966246926
4625) 432 HOUGANG AVE 6, 1.37624747605037, 103.8931285136
4657) 238 PASIR RIS ST 21, 1.37370903858617, 103.96321602063
4652) 837 JURONG WEST ST 81, 1.34307732968771, 103.692906031929
4667) 207 CHOA CHU KANG CTRL, 1.38110321986228, 103.74769368897
4663) 150

4800) 112 PASIR RIS ST 11, 1.36770577441558, 103.955796373988
4803) 135 PASIR RIS ST 11, 1.36454232817849, 103.957472438655
4807) 516 SERANGOON NTH AVE 4, 1.37123838088051, 103.873306943445
4793) 448 HOUGANG AVE 10, 1.37911197134593, 103.895116767173
4801) 442 PASIR RIS DR 6, 1.36893288711175, 103.957951722203
4811) 435 CHOA CHU KANG AVE 4, 1.38513876286097, 103.741050024231
4808) 312 TAMPINES ST 33, 1.35257036820685, 103.957257299848
4799) 57 JLN MA'MOR, 1.32842965533407, 103.85678244292
4796) 824 JURONG WEST ST 81, 1.34640004716841, 103.69413936089
4810) 201 CHOA CHU KANG AVE 1, 1.38213809278539, 103.749542169054
4798) 753 JURONG WEST ST 74, 1.34845660136453, 103.699948982604
4805) 449 PASIR RIS DR 6, 1.37084212079513, 103.958350684252
4809) 231 BISHAN ST 23, 1.35728007993069, 103.845850930421
4812) 438 HOUGANG AVE 8, 1.37804393558863, 103.893152628592
4813) 833 HOUGANG CTRL, 1.37086998152791, 103.889670930929
4816) 724 JURONG WEST ST 72, 1.34508671819794, 103.698185850525
4814) 815 

4948) 36 MOH GUAN TER, 1.28488193684795, 103.83104242125
4937) 803 WOODLANDS ST 81, 1.44035067628585, 103.787094366564
4954) 457 HOUGANG AVE 10, 1.37697434058101, 103.895998625016
4945) 215 BISHAN ST 23, 1.35710190127161, 103.848799750016
4949) 439 CHOA CHU KANG AVE 4, 1.38372413417485, 103.739787430026
4950) 432 CHOA CHU KANG AVE 4, 1.38464414439202, 103.741833630214
4952) 444 HOUGANG AVE 8, 1.37948875169894, 103.893848534648
4946) 212 BISHAN ST 23, 1.35627186049785, 103.84825054364
4953) 453 HOUGANG AVE 10, 1.3784777516539, 103.895888535266
4955) 458 HOUGANG AVE 10, 1.37776288093998, 103.896274487048
4956) 551 HOUGANG ST 51, 1.3784884976611, 103.890722228329
4957) 436 HOUGANG AVE 8, 1.37719783228015, 103.893810723572
4951) 536 HOUGANG ST 52, 1.3771741721863, 103.889474443456
4959) 454 HOUGANG AVE 10, 1.37815921774006, 103.895409744126
4960) 326 JURONG EAST ST 31, 1.3490218244111, 103.729609271898
4958) 441 HOUGANG AVE 8, 1.37845287132506, 103.893940438799
4961) 225 JURONG EAST ST 21,

5093) 486C TAMPINES AVE 9, 1.35886425463447, 103.957299555489
5094) 502 TAMPINES CTRL 1, 1.35641014489862, 103.945141459551
5092) 717 PASIR RIS ST 72, 1.38262059331192, 103.936631122283
5104) 893D WOODLANDS DR 50, 1.43631845206637, 103.789947950224
5101) 128 MARSILING RISE, 1.43745488266891, 103.778927262835
5095) 318 TAMPINES ST 33, 1.35146093987752, 103.956074916044
5097) 326 TAMPINES ST 32, 1.35262855057464, 103.95864453337
5099) 855 WOODLANDS ST 83, 1.44015417263679, 103.793611828946
5107) 615 ANG MO KIO AVE 4, 1.37746341295119, 103.839130090374
5090) 240 PASIR RIS ST 21, 1.37336872347599, 103.962796974808
5098) 123 POTONG PASIR AVE 1, 1.33521063790069, 103.865776268967
5106) 636A YISHUN ST 61, 1.4195429286047, 103.839672741079
5102) 866 WOODLANDS ST 83, 1.4415399886956, 103.792755862349
5109) 650 JLN TENAGA, 1.3318679857149, 103.907573911026
5103) 358 WOODLANDS AVE 5, 1.43368262673441, 103.78387506315
5110) 94C BEDOK NTH AVE 4, 1.33361429610515, 103.942628254514
5096) 497D TAMPINE

5218) 549 PASIR RIS ST 51, 1.36786628480992, 103.953507129107
5229) 935 YISHUN CTRL 1, 1.42518005921711, 103.836596318713
5228) 926 YISHUN CTRL 1, 1.42789934801239, 103.837908520837
5233) 238 CHOA CHU KANG CTRL, 1.37914625858488, 103.74820998984
5234) 278 CHOA CHU KANG AVE 3, 1.38009306194055, 103.743465436354
5232) 278 BISHAN ST 24, 1.3574258202027, 103.843541231528
5236) 292 CHOA CHU KANG AVE 3, 1.37815633473393, 103.739808638278
5237) 543 HOUGANG AVE 8, 1.37785956993058, 103.892020656191
5238) 464 UPP SERANGOON RD, 1.34389769141944, 103.871026678101
5240) 467 HOUGANG AVE 8, 1.37307287188357, 103.89685749928
5239) 465 UPP SERANGOON RD, 1.37190788342411, 103.897012927498
5242) 363 HOUGANG AVE 5, 1.36990038425157, 103.896393480429
5243) 566 HOUGANG ST 51, 1.38127240877127, 103.888435143938
5245) 234 ANG MO KIO AVE 3, 1.36718287740141, 103.836639986274
5222) 303 WOODLANDS ST 31, 1.43095103050767, 103.773761569498
5248) 537 SERANGOON NTH AVE 4, 1.37386057751621, 103.873017935039
5231) 26

5387) 213 PASIR RIS ST 21, 1.36836361180163, 103.96066010554
5391) 247 PASIR RIS ST 21, 1.37068230836737, 103.96250106435
5395) 99A LOR 2 TOA PAYOH, 1.33878534348177, 103.846873055688
5399) 834 JURONG WEST ST 81, 1.34308929877175, 103.694054279271
5398) 832 JURONG WEST ST 81, 1.34402411393529, 103.695220414893
5401) 226 PASIR RIS ST 21, 1.37101230339472, 103.961722370116
5396) 94E BEDOK NTH AVE 4, 1.33330539203383, 103.940906242009
5403) 562 PASIR RIS ST 51, 1.3675903812404, 103.950281806126
5397) 273 CHOA CHU KANG AVE 2, 1.37925043437799, 103.743072730416
5400) 841 JURONG WEST ST 81, 1.34455183440305, 103.692837280438
5393) 315 TAMPINES ST 33, 1.35214170002867, 103.957447937175
5389) 232 PASIR RIS DR 4, 1.37472099992647, 103.961671927365
5388) 560 PASIR RIS ST 51, 1.36676999858984, 103.950425468295
5394) 495B TAMPINES ST 43, 1.36274236096606, 103.951330562087
5402) 230 PASIR RIS ST 21, 1.37289372103764, 103.961153966738
5404) 634 PASIR RIS DR 1, 1.37757160245472, 103.940659584857
5407

5545) 808 WOODLANDS ST 81, 1.44228123978512, 103.78691557368
5540) 516 PASIR RIS ST 52, 1.37414901860681, 103.943539735181
5537) 256 PASIR RIS ST 21, 1.36752457640087, 103.963727043925
5543) 323 WOODLANDS ST 32, 1.43117274894118, 103.77911320353
5547) 253 PASIR RIS ST 21, 1.36815447592499, 103.963074376663
5548) 139 PASIR RIS ST 11, 1.3635179863635, 103.959586721477
5553) 152 PASIR RIS ST 13, 1.36374137521076, 103.962247999674
5555) 8 JOO SENG RD, 1.33520143444299, 103.878702994487
5552) 271 PASIR RIS ST 21, 1.36566783107171, 103.963963178403
5554) 373 TAMPINES ST 34, 1.3560218473311, 103.958780627307
5549) 145 PASIR RIS ST 11, 1.36321945235415, 103.960831858806
5551) 267 PASIR RIS ST 21, 1.36594168369426, 103.963475911176
5556) 322 WOODLANDS ST 32, 1.43151585350574, 103.778881591946
5557) 325 WOODLANDS ST 32, 1.43078891155605, 103.779517722142
5558) 830 WOODLANDS ST 83, 1.43928523903243, 103.790785343534
5550) 252 PASIR RIS ST 21, 1.36802092556576, 103.962716867436
5560) 6 KIM TIAN RD

5688) 579 PASIR RIS ST 53, 1.37442572678737, 103.947355954709
5691) 856F TAMPINES ST 82, 1.35291277412563, 103.938357435494
5694) 334 TAMPINES ST 32, 1.35238951465829, 103.961041591251
5697) 821 WOODLANDS ST 82, 1.4408223847155, 103.790164940634
5698) 309 YISHUN RING RD, 1.43237650422142, 103.840587727638
5681) 754 JURONG WEST ST 74, 1.34866492550953, 103.70037705391
5690) 342 TAMPINES ST 33, 1.35114570469273, 103.961798123148
5699) 760 CHOA CHU KANG NTH 5, 1.39302712654645, 103.747272500906
5686) 648 PASIR RIS DR 10, 1.37880739053832, 103.938681928816
5696) 810 WOODLANDS ST 81, 1.44267221161224, 103.788152306679
5703) 603 CHOA CHU KANG ST 62, 1.39787825146928, 103.744363385914
5700) 752 CHOA CHU KANG NTH 5, 1.39227305010242, 103.747425149246
5704) 259 BOON LAY DR, 1.34551436245234, 103.708635583627
5701) 757 CHOA CHU KANG NTH 5, 1.39284801770148, 103.74591415814
5702) 553 CHOA CHU KANG NTH 6, 1.3958713396608, 103.743519194378
5705) 361 YUNG AN RD, 1.33580354461171, 103.720313655007
57

5823) 613 ELIAS RD, 1.37499586404528, 103.941510592544
5825) 756 PASIR RIS ST 71, 1.37781592005132, 103.933332601455
5826) 714 PASIR RIS ST 72, 1.38264722864523, 103.937556703926
5822) 852 JURONG WEST ST 81, 1.34744620469093, 103.692827944039
5829) 350 TAMPINES ST 33, 1.35385109582854, 103.963082353909
5828) 359 TAMPINES ST 34, 1.35588169299314, 103.961638534274
5827) 710 PASIR RIS ST 72, 1.3819775730856, 103.937637737839
5830) 408 WOODLANDS ST 41, 1.42885248984752, 103.772559237843
5831) 872 WOODLANDS ST 81, 1.44408730145683, 103.789811521995
5833) 841 WOODLANDS ST 82, 1.44350607508298, 103.791708181364
5835) 870 WOODLANDS ST 81, 1.44337343863147, 103.788716250621
5838) 612 CHOA CHU KANG ST 62, 1.40000866051722, 103.744352713589
5832) 873 WOODLANDS ST 81, 1.44329522897943, 103.789746799666
5836) 826 WOODLANDS ST 81, 1.43922359833813, 103.789509510964
5837) 285 BT BATOK EAST AVE 3, 1.34617496464412, 103.757832392184
5834) 844 WOODLANDS AVE 4, 1.44392522478237, 103.793219046325
5842) 61

5969) 855 JURONG WEST ST 81, 1.34691949430163, 103.696188240519
5971) 160 YUNG PING RD, 1.32913047297773, 103.721502089885
5970) 157 YUNG LOH RD, 1.32861633614014, 103.721651422673
5973) 66 KALLANG BAHRU, 1.32066445696203, 103.869914604242
5966) 864 JURONG WEST ST 81, 1.34948340124159, 103.694556118022
5976) 767 PASIR RIS ST 71, 1.37564544660894, 103.935863846869
5972) 859 JURONG WEST ST 81, 1.34923032309478, 103.696100644272
5978) 769 PASIR RIS ST 71, 1.37510622714738, 103.9351471761
5974) 736 PASIR RIS DR 10, 1.37965236410736, 103.937312311942
5975) 750 PASIR RIS ST 71, 1.37820860120297, 103.934646087011
5981) 761 PASIR RIS ST 71, 1.37610193104679, 103.933867337036
5983) 762 PASIR RIS ST 71, 1.37567020169073, 103.933931581433
5980) 760 PASIR RIS ST 71, 1.37640020264297, 103.933539788895
5984) 749 PASIR RIS ST 71, 1.37833993791738, 103.934276500207
5985) 778 PASIR RIS ST 71, 1.37441693620286, 103.938207401151
5986) 781 PASIR RIS ST 71, 1.37386331130291, 103.938574633956
5987) 21 QUEEN

6140) 242 SIMEI ST 5, 1.34315890383485, 103.954188106526
6141) 84A LOR 2 TOA PAYOH, 1.33535500400261, 103.847029911151
6133) 256 SIMEI ST 1, 1.34302556609258, 103.951759832167
6144) 365 WOODLANDS AVE 5, 1.43431838441908, 103.787634150698
6142) 370 WOODLANDS AVE 1, 1.43254270511027, 103.787387733968
6138) 498G TAMPINES ST 45, 1.36227844944127, 103.958121867302
6143) 363 WOODLANDS AVE 5, 1.4339283205204, 103.785927938556
6139) 498L TAMPINES ST 45, 1.36240933130332, 103.957197483189
6145) 708 WOODLANDS DR 70, 1.44005837096467, 103.797369389704
6147) 604 WOODLANDS DR 42, 1.4371352956954, 103.796372143463
6151) 764 CHOA CHU KANG NTH 5, 1.39318129660748, 103.74913495353
6148) 705 WOODLANDS DR 40, 1.43975611226903, 103.796157190366
6146) 711 WOODLANDS DR 70, 1.44123152314849, 103.797483515419
6154) 853 HOUGANG CTRL, 1.36928326720905, 103.894071080721
6153) 850 HOUGANG CTRL, 1.36971638140621, 103.893429934937
6156) 336 TAH CHING RD, 1.33852374734622, 103.723483455608
6155) 323 TAH CHING RD, 1.

6268) 603 WOODLANDS DR 42, 1.43757277585058, 103.796414103464
6262) 705 TAMPINES ST 71, 1.35711597364175, 103.937284846318
6278) 447 BT PANJANG RING RD, 1.38318021667687, 103.771603761569
6280) 322 TAH CHING RD, 1.33687682528474, 103.724556263646
6273) 721 ANG MO KIO AVE 8, 1.37234984781557, 103.847899479721
6285) 512 SERANGOON NTH AVE 4, 1.37151235781968, 103.875246643629
6277) 40 JLN RUMAH TINGGI, 1.28863289349484, 103.810534586582
6274) 625 BT BATOK CTRL, 1.35149041858556, 103.748701610843
6283) 550 SERANGOON NTH AVE 3, 1.37270991331545, 103.870604794931
6287) 544 SERANGOON NTH AVE 3, 1.37440959294033, 103.870931188069
6284) 509 SERANGOON NTH AVE 4, 1.37140997938441, 103.876148952813
6286) 510 SERANGOON NTH AVE 4, 1.3705945092529, 103.875781975365
6281) 30 HOLLAND CL, 1.30774789148086, 103.796627163472
6282) 545 SERANGOON NTH AVE 3, 1.37502513517102, 103.87107476216
6279) 573 HOUGANG ST 51, 1.3776032046872, 103.887546171065
6290) 703 TAMPINES ST 71, 1.35687847904174, 103.93773919806

6442) 546 SERANGOON NTH AVE 3, 1.37454922161147, 103.870230294456
6431) 290E BT BATOK ST 24, 1.34389104771025, 103.757689179709
6432) 628 BT BATOK CTRL, 1.35146739480931, 103.749837547956
6443) 720 TAMPINES ST 72, 1.35938894436607, 103.936070829294
6445) 755 WOODLANDS AVE 4, 1.44529965098561, 103.793269747402
6433) 158 JLN TECK WHYE, 1.37999554881374, 103.756963104815
6447) 786F WOODLANDS DR 60, 1.44624972053447, 103.800417990569
6440) 166 HOUGANG AVE 1, 1.35117566880152, 103.888195279031
6429) 291D BT BATOK ST 24, 1.34351790618134, 103.755391787516
6448) 757 WOODLANDS AVE 4, 1.44621010221646, 103.794598549906
6446) 787D WOODLANDS CRES, 1.44511727056421, 103.801733312456
6444) 750 WOODLANDS AVE 4, 1.44434036268853, 103.793949128001
6449) 798 WOODLANDS DR 72, 1.443718029954, 103.803634259711
6450) 291E BT BATOK ST 24, 1.343453412569, 103.754788281769
6453) 288B BT BATOK ST 25, 1.34600623142926, 103.760505946377
6451) 290A BT BATOK ST 24, 1.34317855232948, 103.756548505542
6454) 170 GANG

6576) 164 JLN TECK WHYE, 1.38115926308689, 103.756362638551
6577) 28 CASSIA CRES, 1.30894452962256, 103.883530101124
6581) 930 HOUGANG ST 91, 1.37548347566834, 103.881278238761
6578) 159 HOUGANG ST 11, 1.35144832512017, 103.879517231789
6582) 941 HOUGANG ST 92, 1.37356291019462, 103.879184657596
6579) 926 HOUGANG ST 91, 1.37610015874638, 103.880942241584
6583) 938 HOUGANG ST 92, 1.3742877202562, 103.879678550369
6590) 285B TOH GUAN RD, 1.33842394940897, 103.746854853224
6585) 940 HOUGANG ST 92, 1.37348307053932, 103.879777763575
6580) 929 HOUGANG ST 91, 1.37608587509748, 103.881497898906
6589) 277 TOH GUAN RD, 1.34131892672099, 103.74672572293
6586) 286A TOH GUAN RD, 1.33866294623076, 103.745669515937
6588) 275 TOH GUAN RD, 1.34106185650379, 103.747964433747
6593) 646 JURONG WEST ST 61, 1.33946114326104, 103.697110638396
6595) 181 STIRLING RD, 1.29438213198317, 103.805560246494
6597) 651 WOODLANDS RING RD, 1.43832201343805, 103.799571960255
6596) 14 LOR 7 TOA PAYOH, 1.33666896706719, 1

6742) 684C WOODLANDS DR 62, 1.44140171851717, 103.803998172951
6745) 470 CHOA CHU KANG AVE 3, 1.37817751599485, 103.737107245589
6744) 469 CHOA CHU KANG AVE 3, 1.37779477244622, 103.73737904885
6748) 962 HOUGANG AVE 9, 1.37774257931559, 103.878389313554
6743) 288E BT BATOK ST 25, 1.34551240744243, 103.758897488955
6746) 669 CHOA CHU KANG CRES, 1.40292361646725, 103.748268655447
6747) 68 CIRCUIT RD, 1.32546801109536, 103.888077424417
6750) 270 TOH GUAN RD, 1.34122974295897, 103.7461193594
6753) 322 SEMBAWANG CL, 1.44555988914785, 103.818296366915
6749) 271 TOH GUAN RD, 1.34168199640726, 103.746245532757
6754) 408 SEMBAWANG DR, 1.45345895920531, 103.817721249079
6759) 626 WOODLANDS AVE 6, 1.43344635284838, 103.800558138968
6757) 236A SERANGOON AVE 2, 1.35387693926748, 103.869510740238
6756) 255 SERANGOON CTRL DR, 1.35506201098257, 103.87087185901
6752) 303 CANBERRA RD, 1.44468992379986, 103.822441620312
6758) 503 WOODLANDS DR 14, 1.43249995976888, 103.791786711705
6751) 349 CORPORATION D

6886) 485C CHOA CHU KANG AVE 5, 1.37479885966148, 103.738969879592
6887) 670A CHOA CHU KANG CRES, 1.4026789634991, 103.747562464245
6888) 951 HOUGANG AVE 9, 1.37572957533559, 103.8781874233
6893) 206C COMPASSVALE LANE, 1.38681829811425, 103.897547410011
6898) 123D RIVERVALE DR, 1.38684496487943, 103.902192105408
6895) 236 COMPASSVALE WALK, 1.3904871662738, 103.899438527283
6892) 336 SEMBAWANG CRES, 1.44695013719977, 103.815574238972
6894) 224A COMPASSVALE WALK, 1.38788229920987, 103.898019126927
6901) 105 RIVERVALE WALK, 1.38215613071495, 103.900711925224
6891) 607 JURONG WEST ST 65, 1.33797491687292, 103.699697593715
6896) 239 COMPASSVALE WALK, 1.39133011799591, 103.898160186775
6897) 225A COMPASSVALE WALK, 1.38764974954714, 103.898706136942
6899) 130 RIVERVALE ST, 1.38944503867735, 103.902653243628
6889) 957 HOUGANG ST 91, 1.37663270919069, 103.879383694154
6900) 132 RIVERVALE ST, 1.39002903680073, 103.903517302026
6890) 642 JURONG WEST ST 61, 1.34036989694199, 103.695839824959
6903)

7036) 636 WOODLANDS RING RD, 1.43686472282189, 103.802701256247
7038) 452 CHOA CHU KANG AVE 4, 1.38031130418576, 103.735332010832
7035) 557 WOODLANDS DR 53, 1.43272193932997, 103.796846435522
7039) 465 CHOA CHU KANG AVE 4, 1.37729601829662, 103.736538815878
3889) 161 BISHAN ST 13, 1.34759183482171, 103.856411840501
7037) 450 CHOA CHU KANG AVE 4, 1.37953908953632, 103.736076503187
7040) 660 CHOA CHU KANG CRES, 1.40102235751598, 103.749862447053
7044) 966 HOUGANG AVE 9, 1.37816668318375, 103.87836616705
7042) 451 CHOA CHU KANG AVE 4, 1.38005209281397, 103.735651375333
7032) 541 WOODLANDS DR 16, 1.42801904350872, 103.793053953282
7046) 517E JURONG WEST ST 52, 1.34456777104819, 103.719018884939
7051) 113 RIVERVALE WALK, 1.38382950520253, 103.901693534901
7049) 223A COMPASSVALE WALK, 1.38813209503832, 103.89725765372
7050) 110 RIVERVALE WALK, 1.38349233528457, 103.900312363452
7047) 667D JURONG WEST ST 65, 1.341877297093, 103.702203679337
7054) 543 WOODLANDS DR 16, 1.42831492534534, 103.793

7189) 684B JURONG WEST ST 64, 1.34383999434612, 103.704216582811
7191) 685A JURONG WEST ST 64, 1.34325837557548, 103.704160122681
7182) 967 HOUGANG AVE 9, 1.37818307588971, 103.878641442114
7185) 668A JURONG WEST ST 64, 1.3418314445114, 103.702880772704
7190) 684C JURONG WEST ST 64, 1.34358659212537, 103.704502970823
7194) 681B JURONG WEST CTRL 1, 1.34481773281614, 103.704952551128
7192) 685B JURONG WEST ST 64, 1.34292038876781, 103.704168834122
7193) 663C JURONG WEST ST 65, 1.33804531435801, 103.702429711458
7197) 473 SEMBAWANG DR, 1.45133628212005, 103.816522350208
7195) 630 JURONG WEST ST 65, 1.34266182765453, 103.700208801281
7196) 59 STRATHMORE AVE, 1.29318965357037, 103.811252591644
7183) 650A JURONG WEST ST 61, 1.33801867728359, 103.696904315506
7198) 481 SEMBAWANG DR, 1.45297628362912, 103.815094118491
7199) 477 SEMBAWANG DR, 1.45208461891806, 103.816554224473
7201) 418 CANBERRA RD, 1.45235459621765, 103.819266367388
7202) 476 SEMBAWANG DR, 1.45154963235734, 103.816931737183
72

7341) 406 ANG MO KIO AVE 10, 1.36200453938712, 103.853879910407
7344) 771 BEDOK RESERVOIR VIEW, 1.33593406213274, 103.938866262286
7349) 623 JURONG WEST ST 61, 1.34032757892166, 103.698247310085
7359) 190A RIVERVALE DR, 1.39508286035406, 103.902774420891
7357) 401 ADMIRALTY LINK, 1.45427018021651, 103.815812639222
7348) 37 TEBAN GDNS RD, 1.32052026841644, 103.742651512921
7360) 121C SENGKANG EAST WAY, 1.38629426559838, 103.905380700368
7358) 340B SEMBAWANG CL, 1.44717581022133, 103.818266688906
7361) 257B COMPASSVALE RD, 1.39259785614922, 103.896980387473
7364) 120B RIVERVALE DR, 1.38579818238123, 103.904394269204
7363) 120A RIVERVALE DR, 1.38593215506966, 103.903984341638
7362) 119B RIVERVALE DR, 1.38436210947006, 103.902965031077
7366) 203D COMPASSVALE RD, 1.38721445178077, 103.895525257108
7368) 10 CHAI CHEE RD, 1.32727572366021, 103.924803599281
7369) 177 LOMPANG RD, 1.38038712496611, 103.76535460069
7365) 251 COMPASSVALE ST, 1.39362917030335, 103.900028614253
7370) 178 LOMPANG RD,

7523) 122D RIVERVALE DR, 1.38709610184489, 103.905723028588
7524) 303C ANCHORVALE LINK, 1.38759793773653, 103.890220332665
7533) 111B DEPOT RD, 1.28116510147179, 103.808471760006
7525) 258B COMPASSVALE RD, 1.39290277450107, 103.897404571333
7528) 200A SENGKANG EAST RD, 1.38700703200166, 103.891964770037
7532) 73A REDHILL RD, 1.28793756967297, 103.816790861272
7531) 311C ANCHORVALE LANE, 1.39157127388497, 103.884436159774
7527) 291D COMPASSVALE ST, 1.39680336272166, 103.898497262093
7530) 260B SENGKANG EAST WAY, 1.39364133502199, 103.895275278312
7534) 651 SENJA LINK, 1.38661244316801, 103.763652921172
7529) 200B SENGKANG EAST RD, 1.3870653779354, 103.892735553222
7510) 606 JURONG WEST ST 65, 1.33793644267156, 103.699282789577
7536) 661A JURONG WEST ST 64, 1.33567944605321, 103.705141174139
7535) 660A JURONG WEST ST 64, 1.33569163767409, 103.704301685702
7538) 661C JURONG WEST ST 64, 1.33607703951673, 103.705050161682
7539) 662A JURONG WEST ST 64, 1.33688578252671, 103.702739749317
7537

7658) 612 SENJA RD, 1.38402104593465, 103.761034236428
7659) 618 SENJA RD, 1.38526615646952, 103.761287937355
7669) 196D PUNGGOL FIELD, 1.39966081419517, 103.907234511303
7660) 610 SENJA RD, 1.38340067966504, 103.761236851817
7663) 684D CHOA CHU KANG CRES, 1.40467820311031, 103.746800063318
7671) 507C WELLINGTON CIRCLE, 1.4517313216515, 103.823451879244
7667) 657A JURONG WEST ST 65, 1.33541318020516, 103.700289313311
7661) 624 SENJA RD, 1.38624340292657, 103.76183758098
7670) 354A ADMIRALTY DR, 1.45006599986269, 103.818890891158
7664) 366 CLEMENTI AVE 2, 1.31254953553443, 103.771676380482
7665) 268A BOON LAY DR, 1.3479800119286, 103.707547320825
7674) 296A COMPASSVALE CRES, 1.3970353252163, 103.899330986212
7666) 274D JURONG WEST AVE 3, 1.35219891849799, 103.704379929183
7668) 674A JURONG WEST ST 65, 1.34446133704193, 103.702315277328
7657) 17 TELOK BLANGAH CRES, 1.27776786253278, 103.821702419401
7676) 301D ANCHORVALE DR, 1.38840523759899, 103.891301833133
7675) 183D RIVERVALE CRES, 1

7792) 184 JELEBU RD, 1.37971095812868, 103.762440084954
7790) 8 CANTONMENT CL, 1.275801012778, 103.839032638772
7794) 684B CHOA CHU KANG CRES, 1.40389957807762, 103.747236264641
7791) 13 CANTONMENT CL, 1.27469944029956, 103.840485373883
7795) 979B BUANGKOK CRES, 1.37951135577177, 103.879376827002
7798) 915 JURONG WEST ST 91, 1.34108918953192, 103.687870332112
7799) 652B JURONG WEST ST 61, 1.33664220672947, 103.697989689004
7797) 673C JURONG WEST ST 65, 1.34471213524955, 103.701313082539
7800) 126D EDGEDALE PLAINS, 1.39378388948021, 103.910981491609
7801) 172B EDGEDALE PLAINS, 1.39572402116348, 103.91180535741
7803) 323A SENGKANG EAST WAY, 1.39271007825759, 103.892999544688
7804) 324A SENGKANG EAST WAY, 1.39346660109152, 103.892056931811
7805) 311D ANCHORVALE LANE, 1.39185683967752, 103.884702425227
7802) 290A COMPASSVALE CRES, 1.3960787618403, 103.896727615807
7808) 320D ANCHORVALE DR, 1.3909522124166, 103.891815990371
7806) 309D ANCHORVALE RD, 1.3908111042137, 103.885496222761
7807) 3

7932) 645 PUNGGOL CTRL, 1.39777616974228, 103.916277438
7935) 101B PUNGGOL FIELD, 1.39784715104396, 103.906436071245
7930) 107B EDGEFIELD PLAINS, 1.39683723523598, 103.907248151565
7933) 104A EDGEFIELD PLAINS, 1.3968057047795, 103.905054187798
7934) 105B EDGEFIELD PLAINS, 1.39720646427031, 103.906002280084
7937) 134 EDGEDALE PLAINS, 1.39233540545797, 103.91018078305
7939) 649 PUNGGOL CTRL, 1.39723823677621, 103.914915439766
7936) 175D PUNGGOL FIELD, 1.39847059579432, 103.90776934521
7938) 118 EDGEFIELD PLAINS, 1.39620706577543, 103.906147061259
7941) 324D SENGKANG EAST WAY, 1.3928443886439, 103.891346931814
7940) 502A WELLINGTON CIRCLE, 1.45093008840551, 103.821415036965
7943) 310B ANCHORVALE RD, 1.39090460679765, 103.884682862492
7945) 158C RIVERVALE CRES, 1.38818825958938, 103.907145829717
7946) 685B WOODLANDS DR 73, 1.44133342839662, 103.806136164821
7944) 403A FERNVALE LANE, 1.3889306090651, 103.873208570293
7948) 19 JLN MEMBINA, 1.2855704164404, 103.826276204595
7942) 318D ANCHORV

8069) 641A PUNGGOL DR, 1.39855482327723, 103.917001591598
8062) 691A CHOA CHU KANG CRES, 1.40115779753494, 103.751471709468
8075) 407B FERNVALE RD, 1.38899739157777, 103.875147967354
8068) 646 PUNGGOL CTRL, 1.398148804861, 103.915780890415
8071) 492 ADMIRALTY LINK, 1.4564743178621, 103.81718135862
8064) 271D JURONG WEST ST 24, 1.35003507101178, 103.704907936078
8072) 509A WELLINGTON CIRCLE, 1.45308000905079, 103.820743432328
8077) 157C RIVERVALE CRES, 1.38775850187872, 103.907729091751
8073) 355A SEMBAWANG WAY, 1.44952989851944, 103.818964193245
8078) 690F WOODLANDS DR 75, 1.44268598668095, 103.807433131663
8079) 981B BUANGKOK CRES, 1.3804698748621, 103.880038005477
8074) 403C FERNVALE LANE, 1.38831848133702, 103.87293569738
8076) 315B ANCHORVALE RD, 1.39217823243959, 103.888323166759
8066) 173A PUNGGOL FIELD, 1.39701308622338, 103.909354092412
8081) 132 EDGEDALE PLAINS, 1.3930694988303, 103.910698497279
8080) 172A EDGEDALE PLAINS, 1.39533467975268, 103.911433937342
8088) 17A TELOK BLA

8213) 204D COMPASSVALE DR, 1.38765175971489, 103.895336027145
8212) 405B FERNVALE LANE, 1.38900200354175, 103.873670202802
8217) 19 JLN TENTERAM, 1.32760704104366, 103.859860478714
8215) 145 LOR 2 TOA PAYOH, 1.33521035428159, 103.846162940767
8216) 35 EUNOS CRES, 1.32110753889088, 103.901372601594
8219) 48 STRATHMORE AVE, 1.29380260290314, 103.807789228113
8221) 152 LOR 2 TOA PAYOH, 1.33416708512554, 103.845891140252
8218) 166B PUNGGOL CTRL, 1.39457812551483, 103.915235013308
8228) 47 JLN TIGA, 1.30876081841943, 103.885032047857
8220) 262C COMPASSVALE ST, 1.3945703423105, 103.895105269913
8225) 306B ANCHORVALE LINK, 1.38967246123379, 103.888614222807
8224) 207C COMPASSVALE LANE, 1.38464244032973, 103.897952220161
8231) 409A FERNVALE RD, 1.38906494156565, 103.877151925492
8230) 403D FERNVALE LANE, 1.38821938378892, 103.873178887951
8227) 114 BEDOK NTH ST 2, 1.33050521254379, 103.93581688525
8233) 508B WELLINGTON CIRCLE, 1.45262510110474, 103.820909521779
8234) 182 BEDOK NTH RD, 1.326869

8352) 337C TAH CHING RD, 1.33719034617161, 103.722003986224
8355) 274B JURONG WEST ST 25, 1.3528655530538, 103.703280481903
8357) 264E COMPASSVALE BOW, 1.38165918663455, 103.895504947189
8354) 988A JURONG WEST ST 93, 1.33648744038913, 103.695614521724
8356) 266B COMPASSVALE BOW, 1.38257935947972, 103.897225252377
8358) 16 MARINE TER, 1.30437184984083, 103.914041662117
8360) 195B PUNGGOL RD, 1.40137201164347, 103.906485652921
8359) 986A JURONG WEST ST 93, 1.33713269339857, 103.695109353427
8363) 195A PUNGGOL RD, 1.40138691564121, 103.90608123416
8365) 220A BEDOK CTRL, 1.32569266983592, 103.934602365058
8362) 266C COMPASSVALE BOW, 1.38271966235889, 103.897362090294
8364) 711 YISHUN AVE 5, 1.42800120289187, 103.827147006794
8361) 28B DOVER CRES, 1.30544397285961, 103.781869025225
8366) 990A JURONG WEST ST 93, 1.33525517762138, 103.69508343694
8368) 79B TOA PAYOH CTRL, 1.33464078301907, 103.847990266882
8367) 264B COMPASSVALE BOW, 1.38128630044125, 103.896543354066
8370) 150 WOODLANDS ST 1

8492) 515B TAMPINES CTRL 7, 1.35696781983179, 103.93866770469
8495) 515D TAMPINES CTRL 7, 1.35696233709253, 103.939269203294
8498) 518B TAMPINES CTRL 7, 1.35636968053202, 103.938669139067
8494) 515C TAMPINES CTRL 7, 1.3569678017343, 103.938986535158
8497) 18C HOLLAND DR, 1.31031629242811, 103.791738859624
8502) 488 ADMIRALTY LINK, 1.45507803962368, 103.81645291747
8501) 518D TAMPINES CTRL 7, 1.3563750896162, 103.939270634189
8493) 518C TAMPINES CTRL 7, 1.35636967092522, 103.938987991759
8496) 303C PUNGGOL CTRL, 1.4040520620826, 103.905300204384
8500) 18B HOLLAND DR, 1.31101768983656, 103.791451916991
8505) 438A SENGKANG WEST AVE, 1.39274604000734, 103.877421746156
8504) 490 ADMIRALTY LINK, 1.45529973571916, 103.817240683169
8503) 489 ADMIRALTY LINK, 1.45495119192133, 103.816819778829
8506) 61C STRATHMORE AVE, 1.29423642591379, 103.812035249623
8508) 487 ADMIRALTY LINK, 1.45545241379364, 103.816118262593
8507) 62A STRATHMORE AVE, 1.29438697520562, 103.811426489782
8511) 61A STRATHMORE A

8654) 307C ANG MO KIO AVE 1, 1.36556100435161, 103.845169497182
8653) 445 YISHUN AVE 11, 1.42319178686724, 103.844627724673
8657) 613A PUNGGOL DR, 1.40442051976244, 103.907861033253
8660) 449 YISHUN RING RD, 1.42260229629233, 103.844247701105
8659) 167D SIMEI LANE, 1.34287368716928, 103.959205140294
8661) 450 YISHUN RING RD, 1.42204534847417, 103.84402117894
8662) 420 CLEMENTI AVE 1, 1.31004548976462, 103.769123845594
8664) 267B PUNGGOL FIELD, 1.40443273898382, 103.897932428343
8655) 425 CLEMENTI AVE 1, 1.30962652347548, 103.771123130536
8663) 612C PUNGGOL DR, 1.40507771619281, 103.90775993572
8666) 212B COMPASSVALE DR, 1.38618514540465, 103.900551157406
8665) 211C COMPASSVALE LANE, 1.38514491225734, 103.899291177027
8667) 212A COMPASSVALE DR, 1.3863982121383, 103.899960032132
8668) 424 CLEMENTI AVE 1, 1.30954013201631, 103.770500847759
8669) 421 CLEMENTI AVE 1, 1.30909798702908, 103.768355913054
8673) 612B PUNGGOL DR, 1.40493858379942, 103.908157161266
8671) 20 TEBAN GDNS RD, 1.323783

8795) 272C PUNGGOL WALK, 1.40285706492636, 103.900067172851
8793) 208C PUNGGOL PL, 1.40094119675936, 103.901144550587
8804) 450A SENGKANG WEST WAY, 1.39446814841577, 103.873506723327
8800) 372 JURONG EAST ST 32, 1.34865823382569, 103.731789499274
8805) 499B TAMPINES AVE 9, 1.35887020526725, 103.956331658876
8803) 207B PUNGGOL PL, 1.40032558873828, 103.900735275237
8807) 207C PUNGGOL PL, 1.40065367495307, 103.900348693368
8806) 180B BOON LAY DR, 1.34783599908392, 103.709070823104
8809) 180C BOON LAY DR, 1.34842916785754, 103.708720552283
8801) 180A BOON LAY DR, 1.34761769756975, 103.708643921054
8802) 622C PUNGGOL CTRL, 1.4006620149821, 103.910914385755
8799) 572A WOODLANDS AVE 1, 1.43086687491645, 103.78955465026
8808) 272D PUNGGOL WALK, 1.40273347530835, 103.90046347534
8810) 208B PUNGGOL PL, 1.40136154264137, 103.901127196589
8811) 211B PUNGGOL WALK, 1.40116989540271, 103.899920878173
8813) 207D PUNGGOL PL, 1.40094652941198, 103.900708420292
8819) 450B SENGKANG WEST WAY, 1.3940477018

8966) 332B ANCHORVALE LINK, 1.39510794708498, 103.891456224923
8955) 166B TECK WHYE CRES, 1.38315989308266, 103.753400918803
8967) 333D ANCHORVALE LINK, 1.39422494446126, 103.892243948665
8957) 470C UPP SERANGOON CRES, 1.37846690134357, 103.900804189301
8968) 333B ANCHORVALE LINK, 1.39457895953303, 103.891425367847
8969) 280A SENGKANG EAST AVE, 1.38616165479022, 103.892278601256
8965) 332A ANCHORVALE LINK, 1.39532164438575, 103.891136801306
8970) 869A TAMPINES AVE 8, 1.35501799093941, 103.93231742743
8961) 590C MONTREAL LINK, 1.44994314368403, 103.82672063438
8975) 431C YISHUN AVE 1, 1.42019719250114, 103.84650450091
8973) 424C YISHUN AVE 11, 1.42325871209596, 103.849154996435
8972) 780F WOODLANDS CRES, 1.44777726469884, 103.801148446244
8962) 281A SENGKANG EAST AVE, 1.38609224063789, 103.891561108663
8971) 869B TAMPINES AVE 8, 1.35485562982979, 103.932709165692
8980) 547B SEGAR RD, 1.38843774527561, 103.769252590551
8978) 318C YISHUN AVE 9, 1.43338279018701, 103.843517908933
8981) 174

9114) 672D EDGEFIELD PLAINS, 1.40759031189113, 103.910923572748
9111) 527C PASIR RIS ST 51, 1.36937329925111, 103.947970231713
9115) 259A PUNGGOL FIELD, 1.40382339950391, 103.895547769394
9122) 890B TAMPINES AVE 1, 1.34690555756363, 103.933409216927
9116) 259C PUNGGOL FIELD, 1.40451590916739, 103.895664857315
9120) 336C ANCHORVALE CRES, 1.39774373171815, 103.88858318745
9123) 342A YISHUN RING RD, 1.43059711114855, 103.84446482342
9126) 505D YISHUN ST 51, 1.41883284175427, 103.844225827265
9125) 505B YISHUN ST 51, 1.41924161070524, 103.844941652639
9117) 667A PUNGGOL DR, 1.40260030998864, 103.913971396177
9121) 330A ANCHORVALE ST, 1.39662723563942, 103.889865427006
9118) 260A PUNGGOL WAY, 1.40479713792879, 103.896616087907
9124) 504D YISHUN ST 51, 1.41833362541375, 103.843721655882
9127) 650 ANG MO KIO ST 61, 1.37769118043958, 103.84274515222
9119) 336A ANCHORVALE CRES, 1.39754408575022, 103.88932509626
9129) 488A CHOA CHU KANG AVE 5, 1.37705950007098, 103.738981398036
9128) 634B SENJA 

9261) 57 TEBAN GDNS RD, 1.32254226544254, 103.737560699176
9266) 868B TAMPINES AVE 8, 1.35592432083149, 103.932912367489
9265) 87 DAWSON RD, 1.2957304268451, 103.809759937443
9262) 256C SUMANG WALK, 1.40540203681824, 103.895910481206
9263) 256D SUMANG WALK, 1.40494870154993, 103.896007686194
9267) 440B CLEMENTI AVE 3, 1.31623936538205, 103.763566375801
9271) 530A PASIR RIS DR 1, 1.37114053931458, 103.949850548422
9270) 530B PASIR RIS DR 1, 1.37168953845762, 103.949502101347
9254) 871C TAMPINES ST 86, 1.35670900289357, 103.931385349285
9272) 668A EDGEFIELD PLAINS, 1.40501880052452, 103.912411867708
9268) 376C HOUGANG ST 32, 1.36406322514465, 103.893679750644
9269) 8A UPP BOON KENG RD, 1.31291757072948, 103.869743094328
9276) 294A COMPASSVALE CRES, 1.39606977416428, 103.895933432889
9274) 470B FERNVALE LINK, 1.39687117865647, 103.879859508141
9264) 678A PUNGGOL DR, 1.40566213236302, 103.908718985826
9273) 88 DAWSON RD, 1.29579395038247, 103.809264765809
9275) 473A FERNVALE ST, 1.39785974

9399) 116B JLN TENTERAM, 1.32754908001444, 103.860807411661
9385) 312C CLEMENTI AVE 4, 1.31952267914453, 103.764025116013
9398) 698A JURONG WEST CTRL 3, 1.341091607667, 103.708023659485
9402) 662B EDGEDALE PLAINS, 1.40172153675655, 103.918690999509
9397) 817B KEAT HONG LINK, 1.37708774602652, 103.748768050663
9396) 805C KEAT HONG CL, 1.37268736243732, 103.743618216079
9389) 314B PUNGGOL WAY, 1.40789778716346, 103.897370752408
9401) 662C EDGEDALE PLAINS, 1.40139181635046, 103.918513893557
9405) 278B COMPASSVALE BOW, 1.38235083780012, 103.890641438035
9404) 286C COMPASSVALE CRES, 1.39811786720081, 103.896423686037
9407) 194B BT BATOK WEST AVE 6, 1.34513283900191, 103.744861953262
9408) 194A BT BATOK WEST AVE 6, 1.34468050128788, 103.7455138661
9403) 314A PUNGGOL WAY, 1.40826187839775, 103.898017940475
9410) 812C CHOA CHU KANG AVE 7, 1.3727609833656, 103.745917783867
9406) 717A WOODLANDS DR 70, 1.44053874571164, 103.798669114626
9412) 802A KEAT HONG CL, 1.37451584184376, 103.74347432386
9

9534) 92A TELOK BLANGAH ST 31, 1.27653169514471, 103.807514165495
9531) 165 BT MERAH CTRL, 1.2829569880635, 103.816934790553
9538) 561A JURONG WEST ST 42, 1.354294109695, 103.719755141086
9535) 90B TELOK BLANGAH ST 31, 1.27728367741324, 103.806916176715
9537) 217B BOON LAY AVE, 1.34972661567521, 103.710830462207
9536) 218B BOON LAY AVE, 1.35032707359938, 103.710888928549
9539) 218D BOON LAY AVE, 1.35085552032825, 103.712083394384
9540) 561B JURONG WEST ST 42, 1.35477102717501, 103.71967262747
9541) 217A BOON LAY AVE, 1.34975768459224, 103.711296415279
9543) 216B BOON LAY AVE, 1.35045319598788, 103.712256991806
9542) 560A JURONG WEST ST 42, 1.3533579932237, 103.719829055981
9546) 165B YUNG KUANG RD, 1.33064472260389, 103.722321863113
9544) 218A BOON LAY AVE, 1.34996858706692, 103.710539626132
9547) 165A YUNG KUANG RD, 1.33072542257431, 103.721913762657
9548) 166B YUNG KUANG RD, 1.3312465772439, 103.722255844894
9545) 164A YUNG KUANG RD, 1.33018740882956, 103.721875506696
9550) 78 LOR LI

9682) 186A BEDOK NTH ST 4, 1.32991427421905, 103.940310513079
9680) 187A BEDOK NTH ST 4, 1.33087094745916, 103.940210775064
9687) 441A BT BATOK WEST AVE 8, 1.35610548541132, 103.739002965384
9681) 187B BEDOK NTH ST 4, 1.33038146607469, 103.940088401203
9686) 440A BT BATOK WEST AVE 8, 1.35522654404615, 103.738772439227
9691) 436A BT BATOK WEST AVE 5, 1.35912883183507, 103.739978327829
9688) 448A BT BATOK WEST AVE 9, 1.35286511774512, 103.740438584574
9689) 448B BT BATOK WEST AVE 9, 1.35314900034194, 103.740846555722
9690) 377 BT BATOK ST 31, 1.35942058239166, 103.750290022372
9693) 292B BT BATOK EAST AVE 6, 1.34477953186313, 103.753961675829
9692) 441C BT BATOK WEST AVE 8, 1.35556816773842, 103.738704484722
9695) 435C BT BATOK WEST AVE 5, 1.35830193962809, 103.739753503555
9696) 451B BT BATOK WEST AVE 6, 1.35248381356888, 103.743414725495
9694) 293B BT BATOK ST 21, 1.34594925522117, 103.754248349899
9697) 450B BT BATOK WEST AVE 6, 1.35235753004524, 103.744395918688
9702) 445A BT BATOK W

A total of 129 seconds are used. <br>
There are 137 flat addresses failed to get their coordinates.

In [18]:
# Check the data stored in the 'flat_address' list
flat_address

['309 ANG MO KIO AVE 1',
 '216 ANG MO KIO AVE 1',
 '211 ANG MO KIO AVE 3',
 '202 ANG MO KIO AVE 3',
 '235 ANG MO KIO AVE 3',
 '232 ANG MO KIO AVE 3',
 '308 ANG MO KIO AVE 1',
 '220 ANG MO KIO AVE 1',
 '219 ANG MO KIO AVE 1',
 '247 ANG MO KIO AVE 3',
 '320 ANG MO KIO AVE 1',
 '252 ANG MO KIO AVE 4',
 '223 ANG MO KIO AVE 1',
 '230 ANG MO KIO AVE 3',
 '329 ANG MO KIO AVE 3',
 '313 ANG MO KIO AVE 3',
 '117 ANG MO KIO AVE 4',
 '110 ANG MO KIO AVE 4',
 '343 ANG MO KIO AVE 3',
 '345 ANG MO KIO AVE 3',
 '346 ANG MO KIO AVE 3',
 '121 ANG MO KIO AVE 3',
 '129 ANG MO KIO AVE 3',
 '130 ANG MO KIO AVE 3',
 '128 ANG MO KIO AVE 3',
 '127 ANG MO KIO AVE 3',
 '126 ANG MO KIO AVE 3',
 '403 ANG MO KIO AVE 10',
 '404 ANG MO KIO AVE 10',
 '405 ANG MO KIO AVE 10',
 '417 ANG MO KIO AVE 10',
 '418 ANG MO KIO AVE 10',
 '419 ANG MO KIO AVE 10',
 '441 ANG MO KIO AVE 10',
 '442 ANG MO KIO AVE 10',
 '443 ANG MO KIO AVE 10',
 '444 ANG MO KIO AVE 10',
 '450 ANG MO KIO AVE 10',
 '435 ANG MO KIO AVE 10',
 '433 ANG MO 

In [19]:
len(flat_address)

9804

In [20]:
# Check the data stored in the 'latitude' list
latitude

['Not found',
 '1.36619678831054',
 '1.369196965617',
 '1.36844644010937',
 '1.36682360872342',
 '1.36834606813391',
 '1.36569665029696',
 '1.36558833593063',
 '1.36598198004505',
 'Not found',
 '1.3655924562134',
 'Not found',
 '1.36604808445916',
 '1.36885445228086',
 '1.3665990830055',
 '1.36664972640598',
 '1.3737170825368',
 '1.37045937010888',
 '1.36837475142719',
 '1.36748702509964',
 '1.36709586875167',
 '1.36970563478325',
 '1.36989498895756',
 '1.37039791675237',
 '1.37083202800001',
 '1.37122322102767',
 '1.37164990020956',
 '1.36126901451361',
 '1.36167767060852',
 '1.36157912717139',
 '1.36495953274783',
 '1.3649460137791',
 '1.36534669720177',
 '1.36605027829032',
 '1.36569241524537',
 '1.36604388871674',
 '1.36660045321147',
 '1.36848406233048',
 '1.36770367670019',
 '1.36807652285135',
 '1.3678915069194',
 '1.36860660305158',
 '1.36915358068729',
 '1.36581960620891',
 '1.36346600647245',
 '1.36275784702216',
 '1.3697435855576',
 '1.37030352965928',
 'Not found',
 '1.366

In [21]:
len(latitude)

9804

In [22]:
# Check the data stored in the 'latitude' list
longitude

['Not found',
 '103.841505011903',
 '103.841666636086',
 '103.844516260527',
 '103.83649123351',
 '103.837196046409',
 '103.844347269095',
 '103.840518883254',
 '103.840654039612',
 'Not found',
 '103.848386744168',
 'Not found',
 '103.838122716883',
 '103.837896397823',
 '103.846874423696',
 '103.850133665442',
 '103.835610469339',
 '103.837419259859',
 '103.849151106677',
 '103.849651723914',
 '103.84966230288',
 '103.843515981311',
 '103.842059049722',
 '103.841878840032',
 '103.843546990613',
 '103.843593321222',
 '103.843644176374',
 '103.854642365822',
 '103.854726492538',
 '103.853805386957',
 '103.855197097728',
 '103.854043379775',
 '103.85415182597',
 '103.854168309853',
 '103.855097870221',
 '103.855368968681',
 '103.855578790668',
 '103.855468149019',
 '103.854214321442',
 '103.854353042615',
 '103.85345502653',
 '103.850808805402',
 '103.851746834886',
 '103.857061597256',
 '103.856702918462',
 '103.858015323667',
 '103.856023138277',
 '103.853455898206',
 'Not found',
 '1

In [23]:
len(longitude)

9804

From the result, there are a total of 137 fail counts. This means that these addresses have no coordinates obtained from API.

This issue will be handled in section 5 below.

### 04.3 Combine the list of hdb addresses, latitude and longitude into a new dataframe

In [24]:
flat_coordinates_onemap = pd.DataFrame({'address' : flat_addresses, 
                                        'latitude' : latitude, 
                                        'longitude' : longitude})

In [25]:
flat_coordinates_onemap.head(10)

address          latitude         longitude
0  309 ANG MO KIO AVE 1         Not found         Not found
1  216 ANG MO KIO AVE 1  1.36619678831054  103.841505011903
2  211 ANG MO KIO AVE 3    1.369196965617  103.841666636086
3  202 ANG MO KIO AVE 3  1.36844644010937  103.844516260527
4  235 ANG MO KIO AVE 3  1.36682360872342   103.83649123351
5  232 ANG MO KIO AVE 3  1.36834606813391  103.837196046409
6  308 ANG MO KIO AVE 1  1.36569665029696  103.844347269095
7  220 ANG MO KIO AVE 1  1.36558833593063  103.840518883254
8  219 ANG MO KIO AVE 1  1.36598198004505  103.840654039612
9  247 ANG MO KIO AVE 3         Not found         Not found

In [26]:
flat_coordinates_onemap.tail(10)

address          latitude         longitude
9794    462A YISHUN AVE 6  1.42763749432623  103.850122944006
9795    462C YISHUN AVE 6  1.42756750243707  103.850898727139
9796    462B YISHUN AVE 6  1.42713422609837  103.850234948425
9797    462D YISHUN AVE 6  1.42803884912514  103.850959508396
9798  676A YISHUN RING RD  1.42145242328288   103.84332790779
9799    469A YISHUN ST 43  1.42469407414992  103.852385726656
9800    469B YISHUN ST 43  1.42438879653642  103.852083098516
9801    673C YISHUN AVE 4  1.42104894176938  103.842206525185
9802    468A YISHUN ST 43  1.42532389372284  103.851843638346
9803    674B YISHUN AVE 4  1.42107254833692  103.843117058752

In [27]:
flat_coordinates_onemap.shape

(9804, 3)

In [28]:
# Export 'flat_address_coordinates_onemap' to Prepared Data folder 
flat_coordinates_onemap.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'flat_coordinates_onemap.csv'))

# 05. Get Missing Coordinates Manually

As mentioned earlier, there are 137 addresses failed to get their coordinates from OneMap API. This might due to the demolition of the blocks through the Selective En bloc Redevelopment Scheme (SERS). For this reason, we are going to obtain their coordinates manually from Google Map and asign to them. We will try to find the postal codes of these addresses from Google and apply them on Google Map. If the postal code is not available and Google Map cannot recognize the address, we will choose the coordinates of the nearest block based on block number. This would not be accurate, but it at least gives us an idea on where were these flats located roughly. <br>
https://www.hdb.gov.sg/residential/living-in-an-hdb-flat/sers-and-upgrading-programmes/sers/sers-projects/completed-sers-projects <br>
https://www.hdb.gov.sg/residential/living-in-an-hdb-flat/sers-and-upgrading-programmes/sers/sers-projects/in-progress-sers-projects

In [29]:
flat_coordinates_onemap.loc[flat_coordinates_onemap['latitude'] == 'Not found']['address']

0           309 ANG MO KIO AVE 1
9           247 ANG MO KIO AVE 3
11          252 ANG MO KIO AVE 4
48         455 ANG MO KIO AVE 10
262               4 HILLVIEW AVE
263               6 HILLVIEW AVE
264               2 HILLVIEW AVE
302             33 TAMAN HO SWEE
318            114 BT MERAH VIEW
340             18 KG BAHRU HILL
341                20 REDHILL CL
342                13 REDHILL CL
343                19 REDHILL CL
346               29 HAVELOCK RD
360            111 BT MERAH VIEW
384                 22 OUTRAM PK
385                  12 SHORT ST
386                  13 SHORT ST
418           323 CLEMENTI AVE 5
419           322 CLEMENTI AVE 5
421           314 CLEMENTI AVE 4
422           313 CLEMENTI AVE 4
429           401 CLEMENTI AVE 1
486             1 JLN PASAR BARU
494                   59 SIMS DR
584              3 TEBAN GDNS RD
585              5 TEBAN GDNS RD
586             10 TEBAN GDNS RD
631              8 YUNG KUANG RD
632             10 YUNG KUANG RD
637       

<b>Below are the coordinates manually input to the 137 addresses above:</b> <br>
Note: The address inside the brackets in each line is used in searching on Google Map. <br>

309 ANG MO KIO AVE 1 - 1.3655169889847343, 103.84396819147089 (308A Ang Mo Kio Ave 1) <br>
247 ANG MO KIO AVE 3 - 1.3682216217409664, 103.8336527877963 (Singapore 560247) <br>
252 ANG MO KIO AVE 4 - 1.369342222650695, 103.83422256323288 (Singapore 560252) <br>
455 ANG MO KIO AVE 10 - 1.3688405731166766, 103.85703511741559 (455 Ang Mo Kio Ave 10) <br>
4 HILLVIEW AVE - 1.3664368833135392, 103.76222396965102 (4 Hillview Ave) <br>
6 HILLVIEW AVE - 1.3662133719859624, 103.76245672057786 (6 Hillview Ave) <br>
2 HILLVIEW AVE - 1.3662026462000616, 103.76239771197721 (2 Hillview Ave) <br>
33 TAMAN HO SWEE - 1.2883291797280607, 103.83174038533298 (Singapore 161033) <br>
114 BT MERAH VIEW - 1.2863867107325693, 103.82228529207782 (Singapore 150114) <br>
18 KG BAHRU HILL - 1.2765777783976922, 103.82997665649788 (Singapore 160018) <br>
20 REDHILL CL - 1.286801643801765, 103.8172859626269 (Singapore 151020) <br>
13 REDHILL CL - 1.2854999115107872, 103.81685556323275 (Singapore 150013) <br>
19 REDHILL CL - 1.2860127029205133, 103.81808404944239 (Singapore 151019) <br>
29 HAVELOCK RD - 1.2891210904821562, 103.83081797431886 (Singapore 160029) <br>
111 BT MERAH VIEW - 1.2862548222415184, 103.82365165648943 (Singapore 150111) <br>
22 OUTRAM PK - 1.2828103563742577, 103.83858979653401 (22 Outram Park) <br>
12 SHORT ST - 1.3028789962902574, 103.85168325166448 (LASALLE College of the Arts) <br>
13 SHORT ST - 1.3028789962902574, 103.85168325166448 (LASALLE College of the Arts) <br>
323 CLEMENTI AVE 5 - 1.3158108171887475, 103.76703436726766 (Singapore 120323) <br>
322 CLEMENTI AVE 5 - 1.316236495800941, 103.766435881021 (Singapore 120322) <br>
314 CLEMENTI AVE 4 - 1.318422518418761, 103.76538188859801 (315 Clementi Avenue 4) <br>
313 CLEMENTI AVE 4 - 1.3190912991344506, 103.76393874736654 (312 Clementi Avenue 4) <br>
401 CLEMENTI AVE 1 - 1.3069446646911946, 103.7681116098622 (Singapore 120401) <br>
1 JLN PASAR BARU - 1.3168125336950494, 103.89820326965021 (Borong Pasar Geylang) <br>
59 SIMS DR - 1.318784652990415, 103.88008490137942 (59 Sims Dr) <br>
3 TEBAN GDNS RD - 1.3217519049381448, 103.74482344240235 (Singapore 600003) <br>
5 TEBAN GDNS RD - 1.3222065990812415, 103.74437327124912 (Singapore 600005) <br>
10 TEBAN GDNS RD - 1.3221922715778167, 103.74263178429575 (Singapore 600010) <br>
8 YUNG KUANG RD - 1.3308797755065527, 103.72239344561419 (Singapore 610008) <br>
10 YUNG KUANG RD - 1.3314581815192128, 103.72195265649171 (Singapore 610010) <br>
145 HU CHING RD - 1.3291068802365438, 103.72334764611611 (Hu Ching Rd) <br>
167 BOON LAY DR - 1.3466973291302466, 103.70618152830032 (Singapore 640167) <br>
168 BOON LAY DR - 1.3469730247979022, 103.70618165648999 (Singapore 640168) <br>
169 BOON LAY DR - 1.3476450724362483, 103.70740006753553 (Singapore 640169) <br>
170 BOON LAY DR - 1.3473275875247912, 103.70730583440012 (Singapore 640170) <br>
172 BOON LAY DR - 1.3465525990524971, 103.7077945157944 (Singapore 640172) <br>
220 BOON LAY AVE - 1.3503128744193946, 103.71196371374799 (Singapore 640220) <br>
20 UPP BOON KENG RD - 1.3142877319758566, 103.87376078200853 (Singapore 380020) <br>
53 TANGLIN HALT RD - 1.300873366742979, 103.79713301931747 (Singapore 142053) <br>
54 TANGLIN HALT RD - 1.3008700727020481, 103.79715160986777 (Singapore 142054) <br>
96 MARGARET DR - 1.299856478092569, 103.8034562223237 (96 Margaret Drive) <br>
24 DOVER CRES - 1.3064596266116126, 103.78280346914953 (Singapore 130024) <br>
173 STIRLING RD - 1.2953599380076886, 103.8045944996247 (173 Stirling Rd) <br>
172 STIRLING RD - 1.295394228129917, 103.80458914378356 (172 Stirling Rd) <br>
52 TANGLIN HALT RD - 1.3008821395274324, 103.79715697427598 (Singapore 142052) <br>
74 C'WEALTH DR - 1.300989084076144, 103.79604097428599 (Singapore 140074) <br>
77 C'WEALTH DR - 1.301470273139427, 103.7957675632403 (Singapore 140077) <br>
79 C'WEALTH DR - 1.301545391133773, 103.79513363318132 (Singapore 140079) <br>
78 C'WEALTH DR - 1.301688435674063, 103.79564629207681 (Singapore 140078) <br>
36 DOVER RD - 1.3000258656886836, 103.78270983437956 (Singapore 130036) <br>
5 SELETAR WEST FARMWAY 6 - 1.396071149317463, 103.86977533869396 (Singapore 798044) <br>
166 LOR 1 TOA PAYOH - 1.3340940263210606, 103.84329745877793 (166 Lor 1 Toa Payoh) <br>
30 LOR 5 TOA PAYOH - 1.33362336095645, 103.854453292076 (Singapore 310030) <br>
1A WOODLANDS CTR RD - 1.4417712984690574, 103.7708907963624 (Singapore 731001) <br>
248 ANG MO KIO AVE 2 - 1.3684988072760422, 103.83237170311509 (Singapore 560248) <br>
454 ANG MO KIO AVE 10 - 1.367897539496139, 103.85793421208811 (Singapore 560454) <br>
83 BEDOK NTH RD - 1.3295455850920797, 103.94026502243322 (Block 82 HDB Bedok North) <br>
31 TAMAN HO SWEE - 1.2887334855943655, 103.83179834072726 (Singapore 164031) <br>
107 DEPOT RD - 1.2815963740997012, 103.80972468295792 (107 Depot Rd) <br>
1 REDHILL CL - 1.2843276927340275, 103.81784602393202 (Singapore 151001) <br>
407 CLEMENTI AVE 1 - 1.3104812154959264, 103.7678115166119 (Singapore 120407) <br>
409 CLEMENTI AVE 1 - 1.3125623724855453, 103.76821794848296 (Singapore 120409) <br>
403 CLEMENTI AVE 1 - 1.3085229540133465, 103.76707350986686 (Singapore 120403) <br>
402 CLEMENTI AVE 1 - 1.307789954116844, 103.76742360979296 (Singapore 120402) <br>
54 SIMS DR - 1.3185404955995619, 103.87880660995062 (Singapore 380054) <br>
62 SIMS DR - 1.3192970325413753, 103.87667188102921 (Singapore 380062) <br>
14 TEBAN GDNS RD - 1.3229017147778237, 103.7408389667023 (Field of Dreams) <br>
5 YUNG PING RD - 1.330170359464526, 103.72186442335509 (Singapore 610005) <br>
6 YUNG PING RD - 1.3303038488929029, 103.72191440431149 (Singapore 610006) <br>
142 HU CHING RD - 1.3291068802365438, 103.72334764611611 (Hu Ching Rd) <br>
171 BOON LAY DR - 1.3467866242790758, 103.70778012524903 (Singapore 640171) <br>
6 UPP BOON KENG RD - 1.3139261114966696, 103.87084409287942 (6 Upper Boon Keng Rd) <br>
76 C'WEALTH DR - 1.3008429101601142, 103.79550129207685 (Singapore 140076) <br>
316 ANG MO KIO AVE 1 - 1.3647397126672844, 103.84664905288479 (316 Ang Mo Kio Ave 1) <br>
110 BT MERAH VIEW - 1.2874444027864156, 103.82270333870572 (Singapore 150110) <br>
22 KG BAHRU HILL - 1.2769419875618853, 103.82935836963716 (22 Silat Rd) <br>
11 SHORT ST - 1.3028789962902574, 103.85168325166448 (LASALLE College of the Arts) <br>
7 TEBAN GDNS RD - 1.321646610152141, 103.74400042304818 (Singapore 600007) <br>
13 TEBAN GDNS RD - 1.3229017147778237, 103.7408389667023 (Field of Dreams) <br>
3 LIM CHU KANG RD - 1.4213081090994577, 103.70420781623427 (Singapore 710003) <br>
10 GHIM MOH RD - 1.3105030133920044, 103.78988852041667 (Singapore 270010) <br>
27A C'WEALTH AVE - 1.2953844530213265, 103.80603633870484 (Singapore 140027) <br>
80 C'WEALTH DR - 1.3019442285514258, 103.79552070312464 (Singapore 140080) <br>
7 HILLVIEW AVE - 1.3658780401799882, 103.76391732283415 (7 Hillview Avenue) <br>
8 HILLVIEW AVE - 1.3663688948516357, 103.7624084363247 (8 Hillview Avenue) <br>
32 LOWER DELTA RD - 1.2889645742650595, 103.82611370994 (48 Lower Delta Rd) <br>
88 ZION RD - 1.2917847509271556, 103.83293731237836 (Singapore 160088) <br>
90 ZION RD - 1.2910245717815583, 103.83369881773812 (Singapore 160090) <br>
8 REDHILL CL - 1.2851824369578624, 103.8167986331832 (Singapore 151008) <br>
3 REDHILL CL - 1.2845610703287467, 103.81669167005137 (Singapore 151003) <br>
51 NILE RD - 1.2797473055291857, 103.84265846047273 (51 Neil Road) <br>
54 NILE RD - 1.2799488141180526, 103.84260959952063 (54 Neil Road) <br>
24 JLN MEMBINA BARAT - 1.2832811287032757, 103.82653184062683 (Singapore 161024) <br>
6 TEBAN GDNS RD - 1.3212062433536578, 103.74401182792772 (Singapore 600006) <br>
35 DOVER RD - 1.299156324478221, 103.78341426876047 (Singapore 130035) <br>
5 BUANGKOK STH FARMWAY 1 - 1.3845278423529006, 103.8985240373611 (Compassvale View) <br>
1 SELETAR WEST FARMWAY 6 - 1.3946329814447982, 103.86998106753063 (Singapore 798042) <br>
2 SELETAR WEST FARMWAY 6 - 1.3947641672830142, 103.87078124543937 (Singapore 798043) <br>
2A WOODLANDS CTR RD - 1.4408120781471487, 103.77085024543479 (Singapore 731002) <br>
138 ALEXANDRA RD - 1.2909986493278949, 103.81773555300782 (136B Alexandra Rd) <br>
142 TIONG BAHRU RD - 1.2860167987575752, 103.82729341802703 (142 Tiong Bahru Rd) <br>
91 ZION RD - 1.2908828260864573, 103.83395829829804 (Singapore 160091) <br>
21 OUTRAM PK - 1.283322012087497, 103.83824591178877 (21 Outram Park) <br>
4 ROCHOR RD - 1.3020007633640034, 103.85495784811125 (4 Rochor Rd) <br>
3 ROCHOR RD - 1.3027627932636705, 103.8552090174156 (3 Rochor Rd) <br>
39A C'WEALTH AVE - 1.298230653234668, 103.80500523774818 (Singapore 140039) <br>
31 DOVER RD - 1.3004422253426429, 103.7838267690774 (Singapore 130031) <br>
89 LOR 2 TOA PAYOH - 1.339307124494977, 103.84692212405666 (89 Lor 2 Toa Payoh) <br>
38 DOVER RD - 1.299062629841912, 103.78219397424145 (Singapore 130038) <br>
17 REDHILL CL - 1.285221270050013, 103.8177752454513 (Singapore 151017) <br>
2 REDHILL CL - 1.284426733178467, 103.81728226876504 (Singapore 151002) <br>
321 CLEMENTI AVE 5 - 1.316592088265206, 103.76633697428424 (Singapore 120321) <br>
7 YUNG KUANG RD - 1.330598729704131, 103.72236826875991 (Singapore 610007) <br>
75 C'WEALTH DR - 1.301213084057412, 103.7959253853315 (Singapore 140075) <br>
167 LOR 1 TOA PAYOH - 1.3336125838574902, 103.84340852344492 (167 Lor 1 Toa Payoh) <br>
6 REDHILL CL - 1.2848011490783848, 103.81712806404295 (Singapore 151006) <br>
10 UPP BOON KENG RD - 1.3142015206597941, 103.8711182156638 (11 Upper Boon Keng Rd) <br>
113 BT MERAH VIEW - 1.286412765091265, 103.82274929208548 (Singapore 150113) <br>
23 KG BAHRU HILL - 1.2772337506414735, 103.82924749848668 (23 Silat Rd) <br>
9 REDHILL CL - 1.2851244369626456, 103.81641495097224 (Singapore 151009) <br>
51 TANGLIN HALT RD - 1.3014265318024425, 103.79770026337631 (49 Tanglin Halt Rd) <br>
5 REDHILL CL - 1.2845567108660667, 103.81779365649693 (Singapore 150005) <br>
89 ZION RD - 1.291552273220678, 103.83345679277531 (Singapore 160089) <br>
16 REDHILL CL - 1.2862001853123681, 103.81705524545117 (Singapore 150016) <br>
18 REDHILL CL - 1.2858596550188974, 103.81779495097402 (Singapore 151018) <br>
21 REDHILL CL - 1.2864675866818298, 103.81766093625994 (Singapore 151021) <br>
14 REDHILL CL - 1.285703347714016, 103.81705224545124 (Singapore 151014) <br>
137 ALEXANDRA RD - 1.2909986493278949, 103.81773555300782 (136B Alexandra Rd) <br>
24 KG BAHRU HILL - 1.277628050622453, 103.82957603406845 (24 Silat Rd) <br>
22 REDHILL CL - 1.286650420795775, 103.8179880270782 (Singapore 151022) <br>
68 DAKOTA CRES - 1.3069593734513223, 103.88779862957955 (68 Dakota Crescent) <br>
11 REDHILL CL - 1.2855060961614753, 103.81621292765057 (Singapore 151011) <br>
7 SELETAR WEST FARMWAY 6 - 1.3964609223019275, 103.87016715218445 (Singapore 798046) <br>
12 REDHILL CL - 1.2861680967484115, 103.8165653353245 (Singapore 151012) <br>
7 REDHILL CL - 1.2849087108418868, 103.81776458655513 (Singapore 151007) <br>
19 KG BAHRU HILL - 1.2771908459602372, 103.82923140523195 (19 Silat Rd) <br>
6 SELETAR WEST FARMWAY 6 - 1.397189888504928, 103.87112093262473 (Singapore 798045)

In [30]:
# Copy the list above into Excel and save it
# Then import that Excel file back to here
flat_coordinates_missing = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'flat_coordinates_missing.csv'))

In [31]:
flat_coordinates_missing

address  latitude   longitude
0        309 ANG MO KIO AVE 1  1.365517  103.843968
1        247 ANG MO KIO AVE 3  1.368222  103.833653
2        252 ANG MO KIO AVE 4  1.369342  103.834223
3       455 ANG MO KIO AVE 10  1.368841  103.857035
4              4 HILLVIEW AVE  1.366437  103.762224
5              6 HILLVIEW AVE  1.366213  103.762457
6              2 HILLVIEW AVE  1.366203  103.762398
7            33 TAMAN HO SWEE  1.288329  103.831740
8           114 BT MERAH VIEW  1.286387  103.822285
9            18 KG BAHRU HILL  1.276578  103.829977
10              20 REDHILL CL  1.286802  103.817286
11              13 REDHILL CL  1.285500  103.816856
12              19 REDHILL CL  1.286013  103.818084
13             29 HAVELOCK RD  1.289121  103.830818
14          111 BT MERAH VIEW  1.286255  103.823652
15               22 OUTRAM PK  1.282810  103.838590
16                12 SHORT ST  1.302879  103.851683
17                13 SHORT ST  1.302879  103.851683
18         323 CLEMENTI AVE 5  1.315811  103.767034
19         322 CLEMENTI AVE 5  1.316236  103.766436
20         314 CLEMENTI AVE 4  1.318423  103.765382
21         313 CLEMENTI AVE 4  1.319091  103.763939
22         401 CLEMENTI AVE 1  1.306945  103.768112
23           1 JLN PASAR BARU  1.316813  103.898203
24                 59 SIMS DR  1.318785  103.880085
25            3 TEBAN GDNS RD  1.321752  103.744823
26            5 TEBAN GDNS RD  1.322207  103.744373
27           10 TEBAN GDNS RD  1.322192  103.742632
28            8 YUNG KUANG RD  1.330880  103.722393
29           10 YUNG KUANG RD  1.331458  103.721953
30            145 HU CHING RD  1.329107  103.723348
31            167 BOON LAY DR  1.346697  103.706181
32            168 BOON LAY DR  1.346973  103.706182
33            169 BOON LAY DR  1.347645  103.707400
34            170 BOON LAY DR  1.347328  103.707306
35            172 BOON LAY DR  1.346553  103.707795
36           220 BOON LAY AVE  1.350313  103.711964
37        20 UPP BOON KENG RD  1.314288  103.873761
38         53 TANGLIN HALT RD  1.300873  103.797133
39         54 TANGLIN HALT RD  1.300870  103.797152
40             96 MARGARET DR  1.299856  103.803456
41              24 DOVER CRES  1.306460  103.782803
42            173 STIRLING RD  1.295360  103.804594
43            172 STIRLING RD  1.295394  103.804589
44         52 TANGLIN HALT RD  1.300882  103.797157
45             74 C'WEALTH DR  1.300989  103.796041
46             77 C'WEALTH DR  1.301470  103.795768
47             79 C'WEALTH DR  1.301545  103.795134
48             78 C'WEALTH DR  1.301688  103.795646
49                36 DOVER RD  1.300026  103.782710
50   5 SELETAR WEST FARMWAY 6  1.396071  103.869775
51        166 LOR 1 TOA PAYOH  1.334094  103.843298
52         30 LOR 5 TOA PAYOH  1.333623  103.854453
53        1A WOODLANDS CTR RD  1.441771  103.770891
54       248 ANG MO KIO AVE 2  1.368499  103.832372
55      454 ANG MO KIO AVE 10  1.367898  103.857934
56            83 BEDOK NTH RD  1.329546  103.940265
57           31 TAMAN HO SWEE  1.288733  103.831798
58               107 DEPOT RD  1.281596  103.809725
59               1 REDHILL CL  1.284328  103.817846
60         407 CLEMENTI AVE 1  1.310481  103.767811
61         409 CLEMENTI AVE 1  1.312562  103.768218
62         403 CLEMENTI AVE 1  1.308523  103.767073
63         402 CLEMENTI AVE 1  1.307790  103.767424
64                 54 SIMS DR  1.318540  103.878807
65                 62 SIMS DR  1.319297  103.876672
66           14 TEBAN GDNS RD  1.322902  103.740839
67             5 YUNG PING RD  1.330170  103.721864
68             6 YUNG PING RD  1.330304  103.721914
69            142 HU CHING RD  1.329107  103.723348
70            171 BOON LAY DR  1.346787  103.707780
71         6 UPP BOON KENG RD  1.313926  103.870844
72             76 C'WEALTH DR  1.300843  103.795501
73       316 ANG MO KIO AVE 1  1.364740  103.846649
74          110 BT MERAH VIEW  1.287444  103.822703
75           22 KG BAHRU HILL  1.276942  103.829358
76                

In [32]:
# Check if there are 137 addresses in 'flat_coordinates_missing'
flat_coordinates_missing.shape

(137, 3)

# 06. Compile A Complete Flat Coordinates List

In [33]:
# 1) Create a deep copy of 'flat_coordinates_onemap'
flat_coordinates_onemap_copy = copy.deepcopy(flat_coordinates_onemap)

In [34]:
# 2) Remove the addresses with missing coordinates in 'flat_coordinates_onemap_copy'
flat_coordinates_onemap_copy = flat_coordinates_onemap_copy.loc[flat_coordinates_onemap_copy['latitude'] != 'Not found']

In [35]:
# Check if there are 9,667 address in 'flat_coordinates_onemap_copy' after removing 137 addresses
flat_coordinates_onemap_copy.shape

(9667, 3)

In [36]:
# 3) Concatnate 'flat_coordinates_onemap_copy' with 'flat_coordinates_missing'
flat_coordinates_complete = pd.concat([flat_coordinates_onemap_copy, flat_coordinates_missing])

In [37]:
flat_coordinates_complete.head()

address          latitude         longitude
1  216 ANG MO KIO AVE 1  1.36619678831054  103.841505011903
2  211 ANG MO KIO AVE 3    1.369196965617  103.841666636086
3  202 ANG MO KIO AVE 3  1.36844644010937  103.844516260527
4  235 ANG MO KIO AVE 3  1.36682360872342   103.83649123351
5  232 ANG MO KIO AVE 3  1.36834606813391  103.837196046409

In [38]:
flat_coordinates_complete.tail()

address  latitude   longitude
132  7 SELETAR WEST FARMWAY 6  1.396461  103.870167
133             12 REDHILL CL  1.286168  103.816565
134              7 REDHILL CL  1.284909  103.817765
135          19 KG BAHRU HILL  1.277191  103.829231
136  6 SELETAR WEST FARMWAY 6   1.39719  103.871121

In [39]:
# Check the final number of rows is the same as the initial 'flat_coordinates_onemap' (9,804 rows)
flat_coordinates_complete.shape

(9804, 3)

In [40]:
flat_coordinates_onemap.shape

(9804, 3)

In [41]:
# Check if there is no missing latitude and longitude in 'flat_coordinates_complete'
flat_coordinates_complete.loc[flat_coordinates_complete['latitude'] == 'Not found']['address']

Series([], Name: address, dtype: object)

In [42]:
flat_coordinates_complete.loc[flat_coordinates_complete['longitude'] == 'Not found']['address']

Series([], Name: address, dtype: object)

In [43]:
# 4) Reset the index
flat_coordinates_complete.reset_index(drop = True, inplace = True)

In [44]:
flat_coordinates_complete.head()

address          latitude         longitude
0  216 ANG MO KIO AVE 1  1.36619678831054  103.841505011903
1  211 ANG MO KIO AVE 3    1.369196965617  103.841666636086
2  202 ANG MO KIO AVE 3  1.36844644010937  103.844516260527
3  235 ANG MO KIO AVE 3  1.36682360872342   103.83649123351
4  232 ANG MO KIO AVE 3  1.36834606813391  103.837196046409

In [45]:
flat_coordinates_complete.tail()

address  latitude   longitude
9799  7 SELETAR WEST FARMWAY 6  1.396461  103.870167
9800             12 REDHILL CL  1.286168  103.816565
9801              7 REDHILL CL  1.284909  103.817765
9802          19 KG BAHRU HILL  1.277191  103.829231
9803  6 SELETAR WEST FARMWAY 6   1.39719  103.871121

In [46]:
# 5) Export 'flat_coordinates_complete' to Prepared Data folder
flat_coordinates_complete.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'flat_coordinates_complete.csv'))

# 07. Add Flat Coordinates to Main Dataframe

In [47]:
# Main dataframe is 'flat_resale'
flat_resale.head()

month        town flat_type block       street_name storey_range  \
0  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
4  1990-01-01  ANG MO KIO    3 ROOM   216  ANG MO KIO AVE 1     04 TO 06   

   floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0            31.0        Improved                 1977        9000.0   
1            31.0        Improved                 1977        6000.0   
2            31.0        Improved                 1977        8000.0   
3            31.0        Improved                 1977        6000.0   
4            73.0  New Generation                 1976       47200.0   

   remaining_lease  row_id               address  
0               86       0  309 ANG MO KIO AVE 1  
1               86       1  309 ANG MO KIO AVE 1  
2               86       2  309 ANG MO KIO AVE 1  
3               86       3  309 ANG MO KIO AVE 1  
4               85       4  216 ANG MO KIO AVE 1

In [48]:
# Merge 'flat_coordinates_complete' and 'flat_resale' on 'address' column using outer join
flat_resale_merge = flat_resale.merge(flat_coordinates_complete, on = ['address'], how = 'outer', indicator = True)

In [49]:
flat_resale_merge.head()

month        town flat_type block       street_name storey_range  \
0  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
4  1990-02-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   

   floor_area_sqm flat_model  lease_commence_date  resale_price  \
0            31.0   Improved                 1977        9000.0   
1            31.0   Improved                 1977        6000.0   
2            31.0   Improved                 1977        8000.0   
3            31.0   Improved                 1977        6000.0   
4            31.0   Improved                 1977        8000.0   

   remaining_lease  row_id               address  latitude   longitude _merge  
0               86       0  309 ANG MO KIO AVE 1  1.365517  103.843968   both  
1               86       1  309 ANG MO KIO AVE 1  1.365517  103.843968   both  
2               86       2  309 ANG MO KIO AVE 1  1.365517  103.843968   both  
3               86       3  309 ANG MO KIO AVE 1  1.365517  103.843968   both  
4               86    1507  309 ANG MO KIO AVE 1  1.365517  103.843968   both

In [50]:
flat_resale_merge.tail()

month    town flat_type block   street_name storey_range  \
915366  2023-07-01  YISHUN    5 ROOM  674B  YISHUN AVE 4     10 TO 12   
915367  2023-07-01  YISHUN    5 ROOM  674B  YISHUN AVE 4     07 TO 09   
915368  2023-08-01  YISHUN    5 ROOM  674B  YISHUN AVE 4     07 TO 09   
915369  2023-12-01  YISHUN    5 ROOM  674B  YISHUN AVE 4     10 TO 12   
915370  2023-12-01  YISHUN    5 ROOM  674B  YISHUN AVE 4     07 TO 09   

        floor_area_sqm flat_model  lease_commence_date  resale_price  \
915366           112.0   Improved                 2018      715000.0   
915367           112.0   Improved                 2018      720000.0   
915368           112.0   Improved                 2018      728000.0   
915369           112.0   Improved                 2018      735000.0   
915370           112.0   Improved                 2018      700000.0   

        remaining_lease  row_id            address          latitude  \
915366               94  915054  674B YISHUN AVE 4  1.42107254833692   
915367               94  915056  674B YISHUN AVE 4  1.42107254833692   
915368               94  915068  674B YISHUN AVE 4  1.42107254833692   
915369               94  915080  674B YISHUN AVE 4  1.42107254833692   
915370               94  915082  674B YISHUN AVE 4  1.42107254833692   

               longitude _merge  
915366  103.843117058752   both  
915367  103.843117058752   both  
915368  103.843117058752   both  
915369  103.843117058752   both  
915370  103.843117058752   both

In [51]:
# Check the merging rate
flat_resale_merge['_merge'].value_counts(dropna = False)

_merge
both          915371
left_only          0
right_only         0
Name: count, dtype: int64

In [52]:
flat_resale_merge.shape

(915371, 16)

The merge between hdb_resale and hdb_address_coordinates_complete is completed at full rate. 

# 07. Export Data

In [53]:
# Rearrange the dataframe based on 'row_id' in asccending order before exporting data
flat_resale_merge.sort_values('row_id', inplace = True)

In [54]:
flat_resale_merge.head()

month        town flat_type block       street_name storey_range  \
0    1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1    1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2    1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3    1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
231  1990-01-01  ANG MO KIO    3 ROOM   216  ANG MO KIO AVE 1     04 TO 06   

     floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0              31.0        Improved                 1977        9000.0   
1              31.0        Improved                 1977        6000.0   
2              31.0        Improved                 1977        8000.0   
3              31.0        Improved                 1977        6000.0   
231            73.0  New Generation                 1976       47200.0   

     remaining_lease  row_id               address          latitude  \
0                 86       0  309 ANG MO KIO AVE 1          1.365517   
1                 86       1  309 ANG MO KIO AVE 1          1.365517   
2                 86       2  309 ANG MO KIO AVE 1          1.365517   
3                 86       3  309 ANG MO KIO AVE 1          1.365517   
231               85       4  216 ANG MO KIO AVE 1  1.36619678831054   

            longitude _merge  
0          103.843968   both  
1          103.843968   both  
2          103.843968   both  
3          103.843968   both  
231  103.841505011903   both

In [55]:
flat_resale_merge.tail()

month    town         flat_type block   street_name storey_range  \
527881  2023-12-01  YISHUN         EXECUTIVE   826  YISHUN ST 81     01 TO 03   
535072  2023-12-01  YISHUN         EXECUTIVE   834  YISHUN ST 81     01 TO 03   
521167  2023-01-01  YISHUN  MULTI-GENERATION   666  YISHUN AVE 4     07 TO 09   
521168  2023-12-01  YISHUN  MULTI-GENERATION   666  YISHUN AVE 4     01 TO 03   
465592  2023-06-01  YISHUN  MULTI-GENERATION   633  YISHUN ST 61     04 TO 06   

        floor_area_sqm        flat_model  lease_commence_date  resale_price  \
527881           142.0         Apartment                 1988      780000.0   
535072           142.0         Apartment                 1988      785000.0   
521167           179.0  Multi Generation                 1987     1080000.0   
521168           179.0  Multi Generation                 1987      975000.0   
465592           159.0  Multi Generation                 1987      935000.0   

        remaining_lease  row_id           address          latitude  \
527881               64  915366  826 YISHUN ST 81  1.41417410336287   
535072               64  915367  834 YISHUN ST 81  1.41508806992271   
521167               63  915368  666 YISHUN AVE 4  1.41899847213282   
521168               63  915369  666 YISHUN AVE 4  1.41899847213282   
465592               63  915370  633 YISHUN ST 61  1.41865757414383   

               longitude _merge  
527881  103.832454191534   both  
535072  103.833999504365   both  
521167  103.840568002498   both  
521168  103.840568002498   both  
465592  103.839842120968   both

In [56]:
# Reset the index
# drop = True, will prevent the old index value be stored as a new column
flat_resale_merge.reset_index(drop = True, inplace = True)

In [57]:
flat_resale_merge.head()

month        town flat_type block       street_name storey_range  \
0  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
4  1990-01-01  ANG MO KIO    3 ROOM   216  ANG MO KIO AVE 1     04 TO 06   

   floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0            31.0        Improved                 1977        9000.0   
1            31.0        Improved                 1977        6000.0   
2            31.0        Improved                 1977        8000.0   
3            31.0        Improved                 1977        6000.0   
4            73.0  New Generation                 1976       47200.0   

   remaining_lease  row_id               address          latitude  \
0               86       0  309 ANG MO KIO AVE 1          1.365517   
1               86       1  309 ANG MO KIO AVE 1          1.365517   
2               86       2  309 ANG MO KIO AVE 1          1.365517   
3               86       3  309 ANG MO KIO AVE 1          1.365517   
4               85       4  216 ANG MO KIO AVE 1  1.36619678831054   

          longitude _merge  
0        103.843968   both  
1        103.843968   both  
2        103.843968   both  
3        103.843968   both  
4  103.841505011903   both

In [58]:
flat_resale_merge.tail()

month    town         flat_type block   street_name storey_range  \
915366  2023-12-01  YISHUN         EXECUTIVE   826  YISHUN ST 81     01 TO 03   
915367  2023-12-01  YISHUN         EXECUTIVE   834  YISHUN ST 81     01 TO 03   
915368  2023-01-01  YISHUN  MULTI-GENERATION   666  YISHUN AVE 4     07 TO 09   
915369  2023-12-01  YISHUN  MULTI-GENERATION   666  YISHUN AVE 4     01 TO 03   
915370  2023-06-01  YISHUN  MULTI-GENERATION   633  YISHUN ST 61     04 TO 06   

        floor_area_sqm        flat_model  lease_commence_date  resale_price  \
915366           142.0         Apartment                 1988      780000.0   
915367           142.0         Apartment                 1988      785000.0   
915368           179.0  Multi Generation                 1987     1080000.0   
915369           179.0  Multi Generation                 1987      975000.0   
915370           159.0  Multi Generation                 1987      935000.0   

        remaining_lease  row_id           address          latitude  \
915366               64  915366  826 YISHUN ST 81  1.41417410336287   
915367               64  915367  834 YISHUN ST 81  1.41508806992271   
915368               63  915368  666 YISHUN AVE 4  1.41899847213282   
915369               63  915369  666 YISHUN AVE 4  1.41899847213282   
915370               63  915370  633 YISHUN ST 61  1.41865757414383   

               longitude _merge  
915366  103.832454191534   both  
915367  103.833999504365   both  
915368  103.840568002498   both  
915369  103.840568002498   both  
915370  103.839842120968   both

In [59]:
# Drop the '_merge' column before exporting
flat_resale_merge.drop(columns = ['_merge'], inplace = True)

In [60]:
flat_resale_merge.head()

month        town flat_type block       street_name storey_range  \
0  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3  1990-01-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
4  1990-01-01  ANG MO KIO    3 ROOM   216  ANG MO KIO AVE 1     04 TO 06   

   floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0            31.0        Improved                 1977        9000.0   
1            31.0        Improved                 1977        6000.0   
2            31.0        Improved                 1977        8000.0   
3            31.0        Improved                 1977        6000.0   
4            73.0  New Generation                 1976       47200.0   

   remaining_lease  row_id               address          latitude  \
0               86       0  309 ANG MO KIO AVE 1          1.365517   
1               86       1  309 ANG MO KIO AVE 1          1.365517   
2               86       2  309 ANG MO KIO AVE 1          1.365517   
3               86       3  309 ANG MO KIO AVE 1          1.365517   
4               85       4  216 ANG MO KIO AVE 1  1.36619678831054   

          longitude  
0        103.843968  
1        103.843968  
2        103.843968  
3        103.843968  
4  103.841505011903

In [61]:
flat_resale_merge.shape

(915371, 15)

In [62]:
# Export 'flat_resale_merge' into Prepared Data folder
flat_resale_merge.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'flat_resale_all_w_coord.csv'))